/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  InvalidAccessError,
  InvalidAccessError$inboundSchema,
  InvalidAccessError$Outbound,
  InvalidAccessError$outboundSchema,
} from "./invalidaccesserror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  ValidationError,
  ValidationError$inboundSchema,
  ValidationError$Outbound,
  ValidationError$outboundSchema,
} from "./validationerror.js";

/**
 * The validation error(s) or invalid access error
 */
export type CreateUnprocessableEntity = ValidationError | InvalidAccessError;

/** @internal */
export const CreateUnprocessableEntity$inboundSchema: z.ZodType<
  CreateUnprocessableEntity,
  z.ZodTypeDef,
  unknown
> = z.union([ValidationError$inboundSchema, InvalidAccessError$inboundSchema]);

/** @internal */
export type CreateUnprocessableEntity$Outbound =
  | ValidationError$Outbound
  | InvalidAccessError$Outbound;

/** @internal */
export const CreateUnprocessableEntity$outboundSchema: z.ZodType<
  CreateUnprocessableEntity$Outbound,
  z.ZodTypeDef,
  CreateUnprocessableEntity
> = z.union([
  ValidationError$outboundSchema,
  InvalidAccessError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateUnprocessableEntity$ {
  /** @deprecated use `CreateUnprocessableEntity$inboundSchema` instead. */
  export const inboundSchema = CreateUnprocessableEntity$inboundSchema;
  /** @deprecated use `CreateUnprocessableEntity$outboundSchema` instead. */
  export const outboundSchema = CreateUnprocessableEntity$outboundSchema;
  /** @deprecated use `CreateUnprocessableEntity$Outbound` instead. */
  export type Outbound = CreateUnprocessableEntity$Outbound;
}

export function createUnprocessableEntityToJSON(
  createUnprocessableEntity: CreateUnprocessableEntity,
): string {
  return JSON.stringify(
    CreateUnprocessableEntity$outboundSchema.parse(createUnprocessableEntity),
  );
}

export function createUnprocessableEntityFromJSON(
  jsonString: string,
): SafeParseResult<CreateUnprocessableEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateUnprocessableEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateUnprocessableEntity' from JSON`,
  );
}
