/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  InvalidAccessError,
  InvalidAccessError$inboundSchema,
  InvalidAccessError$Outbound,
  InvalidAccessError$outboundSchema,
} from "./invalidaccesserror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  ValidationError,
  ValidationError$inboundSchema,
  ValidationError$Outbound,
  ValidationError$outboundSchema,
} from "./validationerror.js";

/**
 * The validation error(s) or invalid access error
 */
export type DeleteUnprocessableEntity = ValidationError | InvalidAccessError;

/** @internal */
export const DeleteUnprocessableEntity$inboundSchema: z.ZodType<
  DeleteUnprocessableEntity,
  z.ZodTypeDef,
  unknown
> = z.union([ValidationError$inboundSchema, InvalidAccessError$inboundSchema]);

/** @internal */
export type DeleteUnprocessableEntity$Outbound =
  | ValidationError$Outbound
  | InvalidAccessError$Outbound;

/** @internal */
export const DeleteUnprocessableEntity$outboundSchema: z.ZodType<
  DeleteUnprocessableEntity$Outbound,
  z.ZodTypeDef,
  DeleteUnprocessableEntity
> = z.union([
  ValidationError$outboundSchema,
  InvalidAccessError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteUnprocessableEntity$ {
  /** @deprecated use `DeleteUnprocessableEntity$inboundSchema` instead. */
  export const inboundSchema = DeleteUnprocessableEntity$inboundSchema;
  /** @deprecated use `DeleteUnprocessableEntity$outboundSchema` instead. */
  export const outboundSchema = DeleteUnprocessableEntity$outboundSchema;
  /** @deprecated use `DeleteUnprocessableEntity$Outbound` instead. */
  export type Outbound = DeleteUnprocessableEntity$Outbound;
}

export function deleteUnprocessableEntityToJSON(
  deleteUnprocessableEntity: DeleteUnprocessableEntity,
): string {
  return JSON.stringify(
    DeleteUnprocessableEntity$outboundSchema.parse(deleteUnprocessableEntity),
  );
}

export function deleteUnprocessableEntityFromJSON(
  jsonString: string,
): SafeParseResult<DeleteUnprocessableEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteUnprocessableEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteUnprocessableEntity' from JSON`,
  );
}
