/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";
import { MoflayError } from "./moflayerror.js";

/**
 * Duplicate Error
 */
export type DuplicateErrorData = {
  error: models.DuplicateErrorError;
};

/**
 * Duplicate Error
 */
export class DuplicateError extends MoflayError {
  error: models.DuplicateErrorError;

  /** The original data that was passed to this error instance. */
  data$: DuplicateErrorData;

  constructor(
    err: DuplicateErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "DuplicateError";
  }
}

/** @internal */
export const DuplicateError$inboundSchema: z.ZodType<
  DuplicateError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => models.DuplicateErrorError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DuplicateError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
