/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  InvalidAccessError,
  InvalidAccessError$inboundSchema,
  InvalidAccessError$Outbound,
  InvalidAccessError$outboundSchema,
} from "./invalidaccesserror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  ValidationError,
  ValidationError$inboundSchema,
  ValidationError$Outbound,
  ValidationError$outboundSchema,
} from "./validationerror.js";

/**
 * The validation error(s) or invalid access error
 */
export type ExpressUnprocessableEntity = ValidationError | InvalidAccessError;

/** @internal */
export const ExpressUnprocessableEntity$inboundSchema: z.ZodType<
  ExpressUnprocessableEntity,
  z.ZodTypeDef,
  unknown
> = z.union([ValidationError$inboundSchema, InvalidAccessError$inboundSchema]);

/** @internal */
export type ExpressUnprocessableEntity$Outbound =
  | ValidationError$Outbound
  | InvalidAccessError$Outbound;

/** @internal */
export const ExpressUnprocessableEntity$outboundSchema: z.ZodType<
  ExpressUnprocessableEntity$Outbound,
  z.ZodTypeDef,
  ExpressUnprocessableEntity
> = z.union([
  ValidationError$outboundSchema,
  InvalidAccessError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExpressUnprocessableEntity$ {
  /** @deprecated use `ExpressUnprocessableEntity$inboundSchema` instead. */
  export const inboundSchema = ExpressUnprocessableEntity$inboundSchema;
  /** @deprecated use `ExpressUnprocessableEntity$outboundSchema` instead. */
  export const outboundSchema = ExpressUnprocessableEntity$outboundSchema;
  /** @deprecated use `ExpressUnprocessableEntity$Outbound` instead. */
  export type Outbound = ExpressUnprocessableEntity$Outbound;
}

export function expressUnprocessableEntityToJSON(
  expressUnprocessableEntity: ExpressUnprocessableEntity,
): string {
  return JSON.stringify(
    ExpressUnprocessableEntity$outboundSchema.parse(expressUnprocessableEntity),
  );
}

export function expressUnprocessableEntityFromJSON(
  jsonString: string,
): SafeParseResult<ExpressUnprocessableEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExpressUnprocessableEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExpressUnprocessableEntity' from JSON`,
  );
}
