/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  InvalidAccessError,
  InvalidAccessError$inboundSchema,
  InvalidAccessError$Outbound,
  InvalidAccessError$outboundSchema,
} from "./invalidaccesserror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  ValidationError,
  ValidationError$inboundSchema,
  ValidationError$Outbound,
  ValidationError$outboundSchema,
} from "./validationerror.js";

/**
 * The validation error(s) or invalid access error
 */
export type GetCustomerUnprocessableEntity =
  | ValidationError
  | InvalidAccessError;

/** @internal */
export const GetCustomerUnprocessableEntity$inboundSchema: z.ZodType<
  GetCustomerUnprocessableEntity,
  z.ZodTypeDef,
  unknown
> = z.union([ValidationError$inboundSchema, InvalidAccessError$inboundSchema]);

/** @internal */
export type GetCustomerUnprocessableEntity$Outbound =
  | ValidationError$Outbound
  | InvalidAccessError$Outbound;

/** @internal */
export const GetCustomerUnprocessableEntity$outboundSchema: z.ZodType<
  GetCustomerUnprocessableEntity$Outbound,
  z.ZodTypeDef,
  GetCustomerUnprocessableEntity
> = z.union([
  ValidationError$outboundSchema,
  InvalidAccessError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomerUnprocessableEntity$ {
  /** @deprecated use `GetCustomerUnprocessableEntity$inboundSchema` instead. */
  export const inboundSchema = GetCustomerUnprocessableEntity$inboundSchema;
  /** @deprecated use `GetCustomerUnprocessableEntity$outboundSchema` instead. */
  export const outboundSchema = GetCustomerUnprocessableEntity$outboundSchema;
  /** @deprecated use `GetCustomerUnprocessableEntity$Outbound` instead. */
  export type Outbound = GetCustomerUnprocessableEntity$Outbound;
}

export function getCustomerUnprocessableEntityToJSON(
  getCustomerUnprocessableEntity: GetCustomerUnprocessableEntity,
): string {
  return JSON.stringify(
    GetCustomerUnprocessableEntity$outboundSchema.parse(
      getCustomerUnprocessableEntity,
    ),
  );
}

export function getCustomerUnprocessableEntityFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomerUnprocessableEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomerUnprocessableEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomerUnprocessableEntity' from JSON`,
  );
}
