/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  InvalidAccessError,
  InvalidAccessError$inboundSchema,
  InvalidAccessError$Outbound,
  InvalidAccessError$outboundSchema,
} from "./invalidaccesserror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  ValidationError,
  ValidationError$inboundSchema,
  ValidationError$Outbound,
  ValidationError$outboundSchema,
} from "./validationerror.js";

/**
 * The validation error(s) or invalid access error
 */
export type GetPaymentUnprocessableEntity =
  | ValidationError
  | InvalidAccessError;

/** @internal */
export const GetPaymentUnprocessableEntity$inboundSchema: z.ZodType<
  GetPaymentUnprocessableEntity,
  z.ZodTypeDef,
  unknown
> = z.union([ValidationError$inboundSchema, InvalidAccessError$inboundSchema]);

/** @internal */
export type GetPaymentUnprocessableEntity$Outbound =
  | ValidationError$Outbound
  | InvalidAccessError$Outbound;

/** @internal */
export const GetPaymentUnprocessableEntity$outboundSchema: z.ZodType<
  GetPaymentUnprocessableEntity$Outbound,
  z.ZodTypeDef,
  GetPaymentUnprocessableEntity
> = z.union([
  ValidationError$outboundSchema,
  InvalidAccessError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPaymentUnprocessableEntity$ {
  /** @deprecated use `GetPaymentUnprocessableEntity$inboundSchema` instead. */
  export const inboundSchema = GetPaymentUnprocessableEntity$inboundSchema;
  /** @deprecated use `GetPaymentUnprocessableEntity$outboundSchema` instead. */
  export const outboundSchema = GetPaymentUnprocessableEntity$outboundSchema;
  /** @deprecated use `GetPaymentUnprocessableEntity$Outbound` instead. */
  export type Outbound = GetPaymentUnprocessableEntity$Outbound;
}

export function getPaymentUnprocessableEntityToJSON(
  getPaymentUnprocessableEntity: GetPaymentUnprocessableEntity,
): string {
  return JSON.stringify(
    GetPaymentUnprocessableEntity$outboundSchema.parse(
      getPaymentUnprocessableEntity,
    ),
  );
}

export function getPaymentUnprocessableEntityFromJSON(
  jsonString: string,
): SafeParseResult<GetPaymentUnprocessableEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPaymentUnprocessableEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPaymentUnprocessableEntity' from JSON`,
  );
}
