/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  InvalidAccessError,
  InvalidAccessError$inboundSchema,
  InvalidAccessError$Outbound,
  InvalidAccessError$outboundSchema,
} from "./invalidaccesserror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  ValidationError,
  ValidationError$inboundSchema,
  ValidationError$Outbound,
  ValidationError$outboundSchema,
} from "./validationerror.js";

/**
 * The validation error(s) or invalid access error
 */
export type GetTransactionUnprocessableEntity =
  | ValidationError
  | InvalidAccessError;

/** @internal */
export const GetTransactionUnprocessableEntity$inboundSchema: z.ZodType<
  GetTransactionUnprocessableEntity,
  z.ZodTypeDef,
  unknown
> = z.union([ValidationError$inboundSchema, InvalidAccessError$inboundSchema]);

/** @internal */
export type GetTransactionUnprocessableEntity$Outbound =
  | ValidationError$Outbound
  | InvalidAccessError$Outbound;

/** @internal */
export const GetTransactionUnprocessableEntity$outboundSchema: z.ZodType<
  GetTransactionUnprocessableEntity$Outbound,
  z.ZodTypeDef,
  GetTransactionUnprocessableEntity
> = z.union([
  ValidationError$outboundSchema,
  InvalidAccessError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionUnprocessableEntity$ {
  /** @deprecated use `GetTransactionUnprocessableEntity$inboundSchema` instead. */
  export const inboundSchema = GetTransactionUnprocessableEntity$inboundSchema;
  /** @deprecated use `GetTransactionUnprocessableEntity$outboundSchema` instead. */
  export const outboundSchema =
    GetTransactionUnprocessableEntity$outboundSchema;
  /** @deprecated use `GetTransactionUnprocessableEntity$Outbound` instead. */
  export type Outbound = GetTransactionUnprocessableEntity$Outbound;
}

export function getTransactionUnprocessableEntityToJSON(
  getTransactionUnprocessableEntity: GetTransactionUnprocessableEntity,
): string {
  return JSON.stringify(
    GetTransactionUnprocessableEntity$outboundSchema.parse(
      getTransactionUnprocessableEntity,
    ),
  );
}

export function getTransactionUnprocessableEntityFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionUnprocessableEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionUnprocessableEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionUnprocessableEntity' from JSON`,
  );
}
