/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  InvalidAccessError,
  InvalidAccessError$inboundSchema,
} from "./invalidaccesserror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  ValidationError,
  ValidationError$inboundSchema,
} from "./validationerror.js";

/**
 * The validation error(s) or invalid access error
 */
export type GetTransactionUnprocessableEntity =
  | ValidationError
  | InvalidAccessError;

/** @internal */
export const GetTransactionUnprocessableEntity$inboundSchema: z.ZodType<
  GetTransactionUnprocessableEntity,
  z.ZodTypeDef,
  unknown
> = z.union([ValidationError$inboundSchema, InvalidAccessError$inboundSchema]);

export function getTransactionUnprocessableEntityFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionUnprocessableEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionUnprocessableEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionUnprocessableEntity' from JSON`,
  );
}
