/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";
import { MoflayError } from "./moflayerror.js";

export type InvalidAccessErrorData = {
  error: models.InvalidAccessErrorError;
  /**
   * Machine-readable error name
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
};

export class InvalidAccessError extends MoflayError {
  error: models.InvalidAccessErrorError;
  /**
   * Machine-readable error name
   */
  code: string;

  /** The original data that was passed to this error instance. */
  data$: InvalidAccessErrorData;

  constructor(
    err: InvalidAccessErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    this.code = err.code;

    this.name = "InvalidAccessError";
  }
}

/** @internal */
export const InvalidAccessError$inboundSchema: z.ZodType<
  InvalidAccessError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => models.InvalidAccessErrorError$inboundSchema),
  code: z.string(),
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new InvalidAccessError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type InvalidAccessError$Outbound = {
  error: models.InvalidAccessErrorError$Outbound;
  code: string;
  message: string;
};

/** @internal */
export const InvalidAccessError$outboundSchema: z.ZodType<
  InvalidAccessError$Outbound,
  z.ZodTypeDef,
  InvalidAccessError
> = z.instanceof(InvalidAccessError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() => models.InvalidAccessErrorError$outboundSchema),
    code: z.string(),
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InvalidAccessError$ {
  /** @deprecated use `InvalidAccessError$inboundSchema` instead. */
  export const inboundSchema = InvalidAccessError$inboundSchema;
  /** @deprecated use `InvalidAccessError$outboundSchema` instead. */
  export const outboundSchema = InvalidAccessError$outboundSchema;
  /** @deprecated use `InvalidAccessError$Outbound` instead. */
  export type Outbound = InvalidAccessError$Outbound;
}
