/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";
import { MoflayError } from "./moflayerror.js";

/**
 * Invalid API Key Error
 */
export type InvalidApiKeyErrorData = {
  error: models.InvalidApiKeyErrorError;
};

/**
 * Invalid API Key Error
 */
export class InvalidApiKeyError extends MoflayError {
  error: models.InvalidApiKeyErrorError;

  /** The original data that was passed to this error instance. */
  data$: InvalidApiKeyErrorData;

  constructor(
    err: InvalidApiKeyErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "InvalidApiKeyError";
  }
}

/** @internal */
export const InvalidApiKeyError$inboundSchema: z.ZodType<
  InvalidApiKeyError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => models.InvalidApiKeyErrorError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new InvalidApiKeyError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
