/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";
import { MoflayError } from "./moflayerror.js";

export type InvalidAccessErrorData = {
  error: models.InvalidAccessErrorError;
  /**
   * Machine-readable error name
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
};

export class InvalidAccessError extends MoflayError {
  error: models.InvalidAccessErrorError;
  /**
   * Machine-readable error name
   */
  code: string;

  /** The original data that was passed to this error instance. */
  data$: InvalidAccessErrorData;

  constructor(
    err: InvalidAccessErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    this.code = err.code;

    this.name = "InvalidAccessError";
  }
}

/** @internal */
export const InvalidAccessError$inboundSchema: z.ZodType<
  InvalidAccessError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => models.InvalidAccessErrorError$inboundSchema),
  code: z.string(),
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new InvalidAccessError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
