/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  InvalidAccessError,
  InvalidAccessError$inboundSchema,
  InvalidAccessError$Outbound,
  InvalidAccessError$outboundSchema,
} from "./invalidaccesserror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  ValidationError,
  ValidationError$inboundSchema,
  ValidationError$Outbound,
  ValidationError$outboundSchema,
} from "./validationerror.js";

/**
 * The validation error(s) or invalid access error
 */
export type ListCustomersUnprocessableEntity =
  | ValidationError
  | InvalidAccessError;

/** @internal */
export const ListCustomersUnprocessableEntity$inboundSchema: z.ZodType<
  ListCustomersUnprocessableEntity,
  z.ZodTypeDef,
  unknown
> = z.union([ValidationError$inboundSchema, InvalidAccessError$inboundSchema]);

/** @internal */
export type ListCustomersUnprocessableEntity$Outbound =
  | ValidationError$Outbound
  | InvalidAccessError$Outbound;

/** @internal */
export const ListCustomersUnprocessableEntity$outboundSchema: z.ZodType<
  ListCustomersUnprocessableEntity$Outbound,
  z.ZodTypeDef,
  ListCustomersUnprocessableEntity
> = z.union([
  ValidationError$outboundSchema,
  InvalidAccessError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListCustomersUnprocessableEntity$ {
  /** @deprecated use `ListCustomersUnprocessableEntity$inboundSchema` instead. */
  export const inboundSchema = ListCustomersUnprocessableEntity$inboundSchema;
  /** @deprecated use `ListCustomersUnprocessableEntity$outboundSchema` instead. */
  export const outboundSchema = ListCustomersUnprocessableEntity$outboundSchema;
  /** @deprecated use `ListCustomersUnprocessableEntity$Outbound` instead. */
  export type Outbound = ListCustomersUnprocessableEntity$Outbound;
}

export function listCustomersUnprocessableEntityToJSON(
  listCustomersUnprocessableEntity: ListCustomersUnprocessableEntity,
): string {
  return JSON.stringify(
    ListCustomersUnprocessableEntity$outboundSchema.parse(
      listCustomersUnprocessableEntity,
    ),
  );
}

export function listCustomersUnprocessableEntityFromJSON(
  jsonString: string,
): SafeParseResult<ListCustomersUnprocessableEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCustomersUnprocessableEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCustomersUnprocessableEntity' from JSON`,
  );
}
