/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  InvalidAccessError,
  InvalidAccessError$inboundSchema,
  InvalidAccessError$Outbound,
  InvalidAccessError$outboundSchema,
} from "./invalidaccesserror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  ValidationError,
  ValidationError$inboundSchema,
  ValidationError$Outbound,
  ValidationError$outboundSchema,
} from "./validationerror.js";

/**
 * The validation error(s) or invalid access error
 */
export type ListTransactionsUnprocessableEntity =
  | ValidationError
  | InvalidAccessError;

/** @internal */
export const ListTransactionsUnprocessableEntity$inboundSchema: z.ZodType<
  ListTransactionsUnprocessableEntity,
  z.ZodTypeDef,
  unknown
> = z.union([ValidationError$inboundSchema, InvalidAccessError$inboundSchema]);

/** @internal */
export type ListTransactionsUnprocessableEntity$Outbound =
  | ValidationError$Outbound
  | InvalidAccessError$Outbound;

/** @internal */
export const ListTransactionsUnprocessableEntity$outboundSchema: z.ZodType<
  ListTransactionsUnprocessableEntity$Outbound,
  z.ZodTypeDef,
  ListTransactionsUnprocessableEntity
> = z.union([
  ValidationError$outboundSchema,
  InvalidAccessError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTransactionsUnprocessableEntity$ {
  /** @deprecated use `ListTransactionsUnprocessableEntity$inboundSchema` instead. */
  export const inboundSchema =
    ListTransactionsUnprocessableEntity$inboundSchema;
  /** @deprecated use `ListTransactionsUnprocessableEntity$outboundSchema` instead. */
  export const outboundSchema =
    ListTransactionsUnprocessableEntity$outboundSchema;
  /** @deprecated use `ListTransactionsUnprocessableEntity$Outbound` instead. */
  export type Outbound = ListTransactionsUnprocessableEntity$Outbound;
}

export function listTransactionsUnprocessableEntityToJSON(
  listTransactionsUnprocessableEntity: ListTransactionsUnprocessableEntity,
): string {
  return JSON.stringify(
    ListTransactionsUnprocessableEntity$outboundSchema.parse(
      listTransactionsUnprocessableEntity,
    ),
  );
}

export function listTransactionsUnprocessableEntityFromJSON(
  jsonString: string,
): SafeParseResult<ListTransactionsUnprocessableEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListTransactionsUnprocessableEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTransactionsUnprocessableEntity' from JSON`,
  );
}
