/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";
import { MoflayError } from "./moflayerror.js";

/**
 * Method Not Allowed Error
 */
export type MethodNotAllowedErrorData = {
  error: models.MethodNotAllowedErrorError;
};

/**
 * Method Not Allowed Error
 */
export class MethodNotAllowedError extends MoflayError {
  error: models.MethodNotAllowedErrorError;

  /** The original data that was passed to this error instance. */
  data$: MethodNotAllowedErrorData;

  constructor(
    err: MethodNotAllowedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "MethodNotAllowedError";
  }
}

/** @internal */
export const MethodNotAllowedError$inboundSchema: z.ZodType<
  MethodNotAllowedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => models.MethodNotAllowedErrorError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new MethodNotAllowedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type MethodNotAllowedError$Outbound = {
  error: models.MethodNotAllowedErrorError$Outbound;
};

/** @internal */
export const MethodNotAllowedError$outboundSchema: z.ZodType<
  MethodNotAllowedError$Outbound,
  z.ZodTypeDef,
  MethodNotAllowedError
> = z.instanceof(MethodNotAllowedError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() => models.MethodNotAllowedErrorError$outboundSchema),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MethodNotAllowedError$ {
  /** @deprecated use `MethodNotAllowedError$inboundSchema` instead. */
  export const inboundSchema = MethodNotAllowedError$inboundSchema;
  /** @deprecated use `MethodNotAllowedError$outboundSchema` instead. */
  export const outboundSchema = MethodNotAllowedError$outboundSchema;
  /** @deprecated use `MethodNotAllowedError$Outbound` instead. */
  export type Outbound = MethodNotAllowedError$Outbound;
}
