/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";
import { MoflayError } from "./moflayerror.js";

/**
 * Method Not Allowed Error
 */
export type MethodNotAllowedErrorData = {
  error: models.MethodNotAllowedErrorError;
};

/**
 * Method Not Allowed Error
 */
export class MethodNotAllowedError extends MoflayError {
  error: models.MethodNotAllowedErrorError;

  /** The original data that was passed to this error instance. */
  data$: MethodNotAllowedErrorData;

  constructor(
    err: MethodNotAllowedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "MethodNotAllowedError";
  }
}

/** @internal */
export const MethodNotAllowedError$inboundSchema: z.ZodType<
  MethodNotAllowedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => models.MethodNotAllowedErrorError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new MethodNotAllowedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
