/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";
import { MoflayError } from "./moflayerror.js";

/**
 * Missing API Key Error
 */
export type MissingApiKeyErrorData = {
  error: models.MissingApiKeyErrorError;
};

/**
 * Missing API Key Error
 */
export class MissingApiKeyError extends MoflayError {
  error: models.MissingApiKeyErrorError;

  /** The original data that was passed to this error instance. */
  data$: MissingApiKeyErrorData;

  constructor(
    err: MissingApiKeyErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "MissingApiKeyError";
  }
}

/** @internal */
export const MissingApiKeyError$inboundSchema: z.ZodType<
  MissingApiKeyError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => models.MissingApiKeyErrorError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new MissingApiKeyError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
