/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";
import { MoflayError } from "./moflayerror.js";

/**
 * Rate Limit Exceeded Error
 */
export type RateLimitExceededErrorData = {
  error: models.RateLimitExceededErrorError;
};

/**
 * Rate Limit Exceeded Error
 */
export class RateLimitExceededError extends MoflayError {
  error: models.RateLimitExceededErrorError;

  /** The original data that was passed to this error instance. */
  data$: RateLimitExceededErrorData;

  constructor(
    err: RateLimitExceededErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "RateLimitExceededError";
  }
}

/** @internal */
export const RateLimitExceededError$inboundSchema: z.ZodType<
  RateLimitExceededError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => models.RateLimitExceededErrorError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new RateLimitExceededError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type RateLimitExceededError$Outbound = {
  error: models.RateLimitExceededErrorError$Outbound;
};

/** @internal */
export const RateLimitExceededError$outboundSchema: z.ZodType<
  RateLimitExceededError$Outbound,
  z.ZodTypeDef,
  RateLimitExceededError
> = z.instanceof(RateLimitExceededError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() => models.RateLimitExceededErrorError$outboundSchema),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RateLimitExceededError$ {
  /** @deprecated use `RateLimitExceededError$inboundSchema` instead. */
  export const inboundSchema = RateLimitExceededError$inboundSchema;
  /** @deprecated use `RateLimitExceededError$outboundSchema` instead. */
  export const outboundSchema = RateLimitExceededError$outboundSchema;
  /** @deprecated use `RateLimitExceededError$Outbound` instead. */
  export type Outbound = RateLimitExceededError$Outbound;
}
