/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  InvalidAccessError,
  InvalidAccessError$inboundSchema,
} from "./invalidaccesserror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  ValidationError,
  ValidationError$inboundSchema,
} from "./validationerror.js";

/**
 * The validation error(s) or invalid access error
 */
export type UpdateUnprocessableEntity = ValidationError | InvalidAccessError;

/** @internal */
export const UpdateUnprocessableEntity$inboundSchema: z.ZodType<
  UpdateUnprocessableEntity,
  z.ZodTypeDef,
  unknown
> = z.union([ValidationError$inboundSchema, InvalidAccessError$inboundSchema]);

export function updateUnprocessableEntityFromJSON(
  jsonString: string,
): SafeParseResult<UpdateUnprocessableEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateUnprocessableEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateUnprocessableEntity' from JSON`,
  );
}
