/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  InvalidAccessError,
  InvalidAccessError$inboundSchema,
  InvalidAccessError$Outbound,
  InvalidAccessError$outboundSchema,
} from "./invalidaccesserror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  ValidationError,
  ValidationError$inboundSchema,
  ValidationError$Outbound,
  ValidationError$outboundSchema,
} from "./validationerror.js";

/**
 * The validation error(s) or invalid access error
 */
export type UpdateUnprocessableEntity = ValidationError | InvalidAccessError;

/** @internal */
export const UpdateUnprocessableEntity$inboundSchema: z.ZodType<
  UpdateUnprocessableEntity,
  z.ZodTypeDef,
  unknown
> = z.union([ValidationError$inboundSchema, InvalidAccessError$inboundSchema]);

/** @internal */
export type UpdateUnprocessableEntity$Outbound =
  | ValidationError$Outbound
  | InvalidAccessError$Outbound;

/** @internal */
export const UpdateUnprocessableEntity$outboundSchema: z.ZodType<
  UpdateUnprocessableEntity$Outbound,
  z.ZodTypeDef,
  UpdateUnprocessableEntity
> = z.union([
  ValidationError$outboundSchema,
  InvalidAccessError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateUnprocessableEntity$ {
  /** @deprecated use `UpdateUnprocessableEntity$inboundSchema` instead. */
  export const inboundSchema = UpdateUnprocessableEntity$inboundSchema;
  /** @deprecated use `UpdateUnprocessableEntity$outboundSchema` instead. */
  export const outboundSchema = UpdateUnprocessableEntity$outboundSchema;
  /** @deprecated use `UpdateUnprocessableEntity$Outbound` instead. */
  export type Outbound = UpdateUnprocessableEntity$Outbound;
}

export function updateUnprocessableEntityToJSON(
  updateUnprocessableEntity: UpdateUnprocessableEntity,
): string {
  return JSON.stringify(
    UpdateUnprocessableEntity$outboundSchema.parse(updateUnprocessableEntity),
  );
}

export function updateUnprocessableEntityFromJSON(
  jsonString: string,
): SafeParseResult<UpdateUnprocessableEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateUnprocessableEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateUnprocessableEntity' from JSON`,
  );
}
