/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";
import { MoflayError } from "./moflayerror.js";

export type ValidationErrorData = {
  error: models.ValidationErrorError;
};

export class ValidationError extends MoflayError {
  error: models.ValidationErrorError;

  /** The original data that was passed to this error instance. */
  data$: ValidationErrorData;

  constructor(
    err: ValidationErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ValidationError";
  }
}

/** @internal */
export const ValidationError$inboundSchema: z.ZodType<
  ValidationError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => models.ValidationErrorError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ValidationError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
