/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expressPay } from "../funcs/expressPay.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Express extends ClientSDK {
  /**
   * Initiate express payment
   *
   * @remarks
   * Initiate an M-Pesa Express (STK Push) payment.
   */
  async pay(
    request: operations.ExpressRequest,
    options?: RequestOptions,
  ): Promise<models.DarajaExpressResponse> {
    return unwrapAsync(expressPay(
      this,
      request,
      options,
    ));
  }
}
