/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsGetOne } from "../funcs/paymentsGetOne.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Payments extends ClientSDK {
  /**
   * Get payment
   *
   * @remarks
   * Get the current status of an Express payment attempt using either the paymentId or related transactionId returned by POST /v1/express.
   *
   * **Permissions**: `transactions.read`
   */
  async getOne(
    request: operations.GetPaymentRequest,
    options?: RequestOptions,
  ): Promise<models.PaymentStatus> {
    return unwrapAsync(paymentsGetOne(
      this,
      request,
      options,
    ));
  }
}
