/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Customers } from "./customers.js";
import { Express } from "./express.js";
import { Payments } from "./payments.js";
import { Transactions } from "./transactions.js";

export class Moflay extends ClientSDK {
  private _customers?: Customers;
  get customers(): Customers {
    return (this._customers ??= new Customers(this._options));
  }

  private _transactions?: Transactions;
  get transactions(): Transactions {
    return (this._transactions ??= new Transactions(this._options));
  }

  private _express?: Express;
  get express(): Express {
    return (this._express ??= new Express(this._options));
  }

  private _payments?: Payments;
  get payments(): Payments {
    return (this._payments ??= new Payments(this._options));
  }
}
