/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @moflay/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx expressPay.example.ts
 */

import { Moflay } from "@moflay/sdk";

const moflay = new Moflay({
  token: "MOFLAY_API_KEY",
});

async function main() {
  const result = await moflay.express.pay({
    idempotencyKey: "express_order_12345",
    requestBody: {
      phoneNumber: "254712345678",
      customerMetadata: {
        "user_preference": "dark_mode",
        "last_login": 1640995200,
        "is_premium": true,
        "account_balance": 1250.75,
        "notifications_enabled": false,
      },
      amount: 526895,
      description: "busily judgementally silently upset usher daddy in edible",
      accountReference: "ORDER123",
      metadata: {
        "user_preference": "dark_mode",
        "last_login": 1640995200,
        "is_premium": true,
        "account_balance": 1250.75,
        "notifications_enabled": false,
      },
    },
  });

  console.log(result);
}

main().catch(console.error);
