workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Moflay API:
        inputs:
            - location: https://api.moflay.com/openapi
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/moflay/moflay/moflay-api
targets:
    moflay:
        target: typescript
        source: Moflay API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/moflay/moflay/moflay-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
