/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteRequest = {
  /**
   * Unique identifier for the customer, prefixed with 'cus_'.
   */
  id: string | null;
};

/** @internal */
export type DeleteRequest$Outbound = {
  id: string | null;
};

/** @internal */
export const DeleteRequest$outboundSchema: z.ZodType<
  DeleteRequest$Outbound,
  z.ZodTypeDef,
  DeleteRequest
> = z.object({
  id: z.nullable(z.string()),
});

export function deleteRequestToJSON(deleteRequest: DeleteRequest): string {
  return JSON.stringify(DeleteRequest$outboundSchema.parse(deleteRequest));
}
