/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ExpressRequestBody = {
  /**
   * Safaricom phone number in local (e.g., 0712345678, 0110123456) or international (e.g., 254712345678, 254110123456) format, transformed to 254XXXXXXXXX for M-PESA STK Push. Supports all Safaricom prefixes (070X, 074X, 0757–0759, 0768–0769, 079X, 0110–0117).
   */
  phoneNumber?: string | undefined;
  customerId?: string | undefined;
  customerName?: string | undefined;
  customerDescription?: string | undefined;
  /**
   * Key-value object allowing you to store additional information.
   *
   * @remarks
   *
   * **Key Requirements:**
   * - Must be a string
   * - Maximum length of 40 characters
   *
   * **Value Types:**
   * - String (maximum 500 characters)
   * - Integer
   * - Floating-point number
   * - Boolean
   *
   * **Limits:**
   * - Maximum of 50 key-value pairs
   */
  customerMetadata?: { [k: string]: models.Metadata } | undefined;
  amount: number;
  description: string;
  /**
   * Short alphanumeric reference shown by M-Pesa and stored with the payment, such as an order or invoice number. If omitted, Moflay uses your configured default account reference.
   */
  accountReference?: string | undefined;
  /**
   * Key-value object allowing you to store additional information.
   *
   * @remarks
   *
   * **Key Requirements:**
   * - Must be a string
   * - Maximum length of 40 characters
   *
   * **Value Types:**
   * - String (maximum 500 characters)
   * - Integer
   * - Floating-point number
   * - Boolean
   *
   * **Limits:**
   * - Maximum of 50 key-value pairs
   */
  metadata?: { [k: string]: models.Metadata } | undefined;
};

export type ExpressRequest = {
  /**
   * Optional idempotency key used to safely retry the same Express payment request without creating duplicate payment attempts.
   */
  idempotencyKey?: string | undefined;
  requestBody: ExpressRequestBody;
};

/** @internal */
export const ExpressRequestBody$inboundSchema: z.ZodType<
  ExpressRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  phoneNumber: z.string().optional(),
  customerId: z.string().optional(),
  customerName: z.string().optional(),
  customerDescription: z.string().optional(),
  customerMetadata: z.record(models.Metadata$inboundSchema).optional(),
  amount: z.number().int(),
  description: z.string(),
  accountReference: z.string().optional(),
  metadata: z.record(models.Metadata$inboundSchema).optional(),
});

/** @internal */
export type ExpressRequestBody$Outbound = {
  phoneNumber?: string | undefined;
  customerId?: string | undefined;
  customerName?: string | undefined;
  customerDescription?: string | undefined;
  customerMetadata?: { [k: string]: models.Metadata$Outbound } | undefined;
  amount: number;
  description: string;
  accountReference?: string | undefined;
  metadata?: { [k: string]: models.Metadata$Outbound } | undefined;
};

/** @internal */
export const ExpressRequestBody$outboundSchema: z.ZodType<
  ExpressRequestBody$Outbound,
  z.ZodTypeDef,
  ExpressRequestBody
> = z.object({
  phoneNumber: z.string().optional(),
  customerId: z.string().optional(),
  customerName: z.string().optional(),
  customerDescription: z.string().optional(),
  customerMetadata: z.record(models.Metadata$outboundSchema).optional(),
  amount: z.number().int(),
  description: z.string(),
  accountReference: z.string().optional(),
  metadata: z.record(models.Metadata$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExpressRequestBody$ {
  /** @deprecated use `ExpressRequestBody$inboundSchema` instead. */
  export const inboundSchema = ExpressRequestBody$inboundSchema;
  /** @deprecated use `ExpressRequestBody$outboundSchema` instead. */
  export const outboundSchema = ExpressRequestBody$outboundSchema;
  /** @deprecated use `ExpressRequestBody$Outbound` instead. */
  export type Outbound = ExpressRequestBody$Outbound;
}

export function expressRequestBodyToJSON(
  expressRequestBody: ExpressRequestBody,
): string {
  return JSON.stringify(
    ExpressRequestBody$outboundSchema.parse(expressRequestBody),
  );
}

export function expressRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<ExpressRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExpressRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExpressRequestBody' from JSON`,
  );
}

/** @internal */
export const ExpressRequest$inboundSchema: z.ZodType<
  ExpressRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Idempotency-Key": z.string().optional(),
  RequestBody: z.lazy(() => ExpressRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Idempotency-Key": "idempotencyKey",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type ExpressRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  RequestBody: ExpressRequestBody$Outbound;
};

/** @internal */
export const ExpressRequest$outboundSchema: z.ZodType<
  ExpressRequest$Outbound,
  z.ZodTypeDef,
  ExpressRequest
> = z.object({
  idempotencyKey: z.string().optional(),
  requestBody: z.lazy(() => ExpressRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "Idempotency-Key",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExpressRequest$ {
  /** @deprecated use `ExpressRequest$inboundSchema` instead. */
  export const inboundSchema = ExpressRequest$inboundSchema;
  /** @deprecated use `ExpressRequest$outboundSchema` instead. */
  export const outboundSchema = ExpressRequest$outboundSchema;
  /** @deprecated use `ExpressRequest$Outbound` instead. */
  export type Outbound = ExpressRequest$Outbound;
}

export function expressRequestToJSON(expressRequest: ExpressRequest): string {
  return JSON.stringify(ExpressRequest$outboundSchema.parse(expressRequest));
}

export function expressRequestFromJSON(
  jsonString: string,
): SafeParseResult<ExpressRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExpressRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExpressRequest' from JSON`,
  );
}
