/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetPaymentRequest = {
  /**
   * Payment lookup identifier. Use a paymentId prefixed with 'pay_' or the related transactionId prefixed with 'trxn_'.
   */
  id: string;
};

/** @internal */
export const GetPaymentRequest$inboundSchema: z.ZodType<
  GetPaymentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetPaymentRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetPaymentRequest$outboundSchema: z.ZodType<
  GetPaymentRequest$Outbound,
  z.ZodTypeDef,
  GetPaymentRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPaymentRequest$ {
  /** @deprecated use `GetPaymentRequest$inboundSchema` instead. */
  export const inboundSchema = GetPaymentRequest$inboundSchema;
  /** @deprecated use `GetPaymentRequest$outboundSchema` instead. */
  export const outboundSchema = GetPaymentRequest$outboundSchema;
  /** @deprecated use `GetPaymentRequest$Outbound` instead. */
  export type Outbound = GetPaymentRequest$Outbound;
}

export function getPaymentRequestToJSON(
  getPaymentRequest: GetPaymentRequest,
): string {
  return JSON.stringify(
    GetPaymentRequest$outboundSchema.parse(getPaymentRequest),
  );
}

export function getPaymentRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetPaymentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPaymentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPaymentRequest' from JSON`,
  );
}
