/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetTransactionRequest = {
  /**
   * Unique identifier for the transaction, prefixed with 'trxn_'
   */
  id: string;
};

/** @internal */
export type GetTransactionRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetTransactionRequest$outboundSchema: z.ZodType<
  GetTransactionRequest$Outbound,
  z.ZodTypeDef,
  GetTransactionRequest
> = z.object({
  id: z.string(),
});

export function getTransactionRequestToJSON(
  getTransactionRequest: GetTransactionRequest,
): string {
  return JSON.stringify(
    GetTransactionRequest$outboundSchema.parse(getTransactionRequest),
  );
}
