/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const ListTransactionsSortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type ListTransactionsSortOrder = ClosedEnum<
  typeof ListTransactionsSortOrder
>;

export const ListTransactionsSortBy = {
  CreatedAt: "createdAt",
  PaidAt: "paidAt",
  FailedAt: "failedAt",
  Amount: "amount",
  Status: "status",
  PhoneNumber: "phoneNumber",
  ProcessedAt: "processedAt",
} as const;
export type ListTransactionsSortBy = ClosedEnum<typeof ListTransactionsSortBy>;

export type ListTransactionsRequest = {
  /**
   * Search for transactions by description, phone number, or receipt number
   */
  q?: string | null | undefined;
  /**
   * Cursor for pagination, representing the last item from the previous page
   */
  cursor?: string | null | undefined;
  /**
   * Filter transactions by specific customer ID
   */
  customerId?: string | null | undefined;
  /**
   * Array of transaction statuses to filter by. Available statuses: 'initiating', 'pending', 'completed', 'failed', 'unknown'
   */
  statuses?: Array<models.TransactionStatus> | null | undefined;
  /**
   * Amount range as [min, max] in cents to filter transactions by monetary value. Example: [10000, 50000] for KES 100.00 to KES 500.00
   */
  amountRange?: Array<number> | null | undefined;
  /**
   * Array of specific amounts (as strings in KES) to filter transactions by exact values. Values are converted to cents internally.
   */
  amount?: Array<string> | null | undefined;
  /**
   * The number of transactions to return (1-100)
   */
  limit?: number | undefined;
  /**
   * Start date (inclusive) for filtering transactions in ISO 8601 format
   */
  start?: Date | null | undefined;
  /**
   * End date (inclusive) for filtering transactions in ISO 8601 format
   */
  end?: Date | null | undefined;
  sortOrder?: ListTransactionsSortOrder | undefined;
  sortBy?: ListTransactionsSortBy | undefined;
};

export type ListTransactionsResponse = {
  result: models.TransactionListResponse;
};

/** @internal */
export const ListTransactionsSortOrder$inboundSchema: z.ZodNativeEnum<
  typeof ListTransactionsSortOrder
> = z.nativeEnum(ListTransactionsSortOrder);

/** @internal */
export const ListTransactionsSortOrder$outboundSchema: z.ZodNativeEnum<
  typeof ListTransactionsSortOrder
> = ListTransactionsSortOrder$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTransactionsSortOrder$ {
  /** @deprecated use `ListTransactionsSortOrder$inboundSchema` instead. */
  export const inboundSchema = ListTransactionsSortOrder$inboundSchema;
  /** @deprecated use `ListTransactionsSortOrder$outboundSchema` instead. */
  export const outboundSchema = ListTransactionsSortOrder$outboundSchema;
}

/** @internal */
export const ListTransactionsSortBy$inboundSchema: z.ZodNativeEnum<
  typeof ListTransactionsSortBy
> = z.nativeEnum(ListTransactionsSortBy);

/** @internal */
export const ListTransactionsSortBy$outboundSchema: z.ZodNativeEnum<
  typeof ListTransactionsSortBy
> = ListTransactionsSortBy$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTransactionsSortBy$ {
  /** @deprecated use `ListTransactionsSortBy$inboundSchema` instead. */
  export const inboundSchema = ListTransactionsSortBy$inboundSchema;
  /** @deprecated use `ListTransactionsSortBy$outboundSchema` instead. */
  export const outboundSchema = ListTransactionsSortBy$outboundSchema;
}

/** @internal */
export const ListTransactionsRequest$inboundSchema: z.ZodType<
  ListTransactionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  q: z.nullable(z.string()).optional(),
  cursor: z.nullable(z.string()).optional(),
  customerId: z.nullable(z.string()).optional(),
  statuses: z.nullable(z.array(models.TransactionStatus$inboundSchema))
    .optional(),
  amountRange: z.nullable(z.array(z.number())).optional(),
  amount: z.nullable(z.array(z.string())).optional(),
  limit: z.number().default(10),
  start: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  end: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  sortOrder: ListTransactionsSortOrder$inboundSchema.default("desc"),
  sortBy: ListTransactionsSortBy$inboundSchema.default("createdAt"),
});

/** @internal */
export type ListTransactionsRequest$Outbound = {
  q?: string | null | undefined;
  cursor?: string | null | undefined;
  customerId?: string | null | undefined;
  statuses?: Array<string> | null | undefined;
  amountRange?: Array<number> | null | undefined;
  amount?: Array<string> | null | undefined;
  limit: number;
  start?: string | null | undefined;
  end?: string | null | undefined;
  sortOrder: string;
  sortBy: string;
};

/** @internal */
export const ListTransactionsRequest$outboundSchema: z.ZodType<
  ListTransactionsRequest$Outbound,
  z.ZodTypeDef,
  ListTransactionsRequest
> = z.object({
  q: z.nullable(z.string()).optional(),
  cursor: z.nullable(z.string()).optional(),
  customerId: z.nullable(z.string()).optional(),
  statuses: z.nullable(z.array(models.TransactionStatus$outboundSchema))
    .optional(),
  amountRange: z.nullable(z.array(z.number())).optional(),
  amount: z.nullable(z.array(z.string())).optional(),
  limit: z.number().default(10),
  start: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  end: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  sortOrder: ListTransactionsSortOrder$outboundSchema.default("desc"),
  sortBy: ListTransactionsSortBy$outboundSchema.default("createdAt"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTransactionsRequest$ {
  /** @deprecated use `ListTransactionsRequest$inboundSchema` instead. */
  export const inboundSchema = ListTransactionsRequest$inboundSchema;
  /** @deprecated use `ListTransactionsRequest$outboundSchema` instead. */
  export const outboundSchema = ListTransactionsRequest$outboundSchema;
  /** @deprecated use `ListTransactionsRequest$Outbound` instead. */
  export type Outbound = ListTransactionsRequest$Outbound;
}

export function listTransactionsRequestToJSON(
  listTransactionsRequest: ListTransactionsRequest,
): string {
  return JSON.stringify(
    ListTransactionsRequest$outboundSchema.parse(listTransactionsRequest),
  );
}

export function listTransactionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListTransactionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTransactionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTransactionsRequest' from JSON`,
  );
}

/** @internal */
export const ListTransactionsResponse$inboundSchema: z.ZodType<
  ListTransactionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: models.TransactionListResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type ListTransactionsResponse$Outbound = {
  Result: models.TransactionListResponse$Outbound;
};

/** @internal */
export const ListTransactionsResponse$outboundSchema: z.ZodType<
  ListTransactionsResponse$Outbound,
  z.ZodTypeDef,
  ListTransactionsResponse
> = z.object({
  result: models.TransactionListResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTransactionsResponse$ {
  /** @deprecated use `ListTransactionsResponse$inboundSchema` instead. */
  export const inboundSchema = ListTransactionsResponse$inboundSchema;
  /** @deprecated use `ListTransactionsResponse$outboundSchema` instead. */
  export const outboundSchema = ListTransactionsResponse$outboundSchema;
  /** @deprecated use `ListTransactionsResponse$Outbound` instead. */
  export type Outbound = ListTransactionsResponse$Outbound;
}

export function listTransactionsResponseToJSON(
  listTransactionsResponse: ListTransactionsResponse,
): string {
  return JSON.stringify(
    ListTransactionsResponse$outboundSchema.parse(listTransactionsResponse),
  );
}

export function listTransactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListTransactionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTransactionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTransactionsResponse' from JSON`,
  );
}
