/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * The order in which to sort results. Defaults to `'desc'`. Use `'asc'` for ascending (oldest first) or `'desc'` for descending (newest first).
 */
export const ListCustomersSortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The order in which to sort results. Defaults to `'desc'`. Use `'asc'` for ascending (oldest first) or `'desc'` for descending (newest first).
 */
export type ListCustomersSortOrder = ClosedEnum<typeof ListCustomersSortOrder>;

/**
 * The field to sort results by. Defaults to `'createdAt'`. Supported fields include any sortable customer property.
 */
export const ListCustomersSortBy = {
  CreatedAt: "createdAt",
  Name: "name",
  LastActiveAt: "lastActiveAt",
  CountryCode: "countryCode",
  PhoneNumber: "phoneNumber",
  FirstTransactionAt: "firstTransactionAt",
  IsActive: "isActive",
  IsVerified: "isVerified",
} as const;
/**
 * The field to sort results by. Defaults to `'createdAt'`. Supported fields include any sortable customer property.
 */
export type ListCustomersSortBy = ClosedEnum<typeof ListCustomersSortBy>;

export type ListCustomersRequest = {
  /**
   * Search for a customer by name, phone number, or description
   */
  q?: string | null | undefined;
  /**
   * Cursor for pagination, representing the last item from the previous page
   */
  cursor?: string | null | undefined;
  /**
   * The number of customers to return (1-100)
   */
  limit?: number | undefined;
  /**
   * Start date (inclusive) for filtering customers in ISO 8601 format
   */
  start?: Date | null | undefined;
  /**
   * End date (inclusive) for filtering customers in ISO 8601 format
   */
  end?: Date | null | undefined;
  /**
   * The order in which to sort results. Defaults to `'desc'`. Use `'asc'` for ascending (oldest first) or `'desc'` for descending (newest first).
   */
  sortOrder?: ListCustomersSortOrder | undefined;
  /**
   * The field to sort results by. Defaults to `'createdAt'`. Supported fields include any sortable customer property.
   */
  sortBy?: ListCustomersSortBy | undefined;
};

export type ListCustomersResponse = {
  result: models.CustomerListResponse;
};

/** @internal */
export const ListCustomersSortOrder$inboundSchema: z.ZodNativeEnum<
  typeof ListCustomersSortOrder
> = z.nativeEnum(ListCustomersSortOrder);

/** @internal */
export const ListCustomersSortOrder$outboundSchema: z.ZodNativeEnum<
  typeof ListCustomersSortOrder
> = ListCustomersSortOrder$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListCustomersSortOrder$ {
  /** @deprecated use `ListCustomersSortOrder$inboundSchema` instead. */
  export const inboundSchema = ListCustomersSortOrder$inboundSchema;
  /** @deprecated use `ListCustomersSortOrder$outboundSchema` instead. */
  export const outboundSchema = ListCustomersSortOrder$outboundSchema;
}

/** @internal */
export const ListCustomersSortBy$inboundSchema: z.ZodNativeEnum<
  typeof ListCustomersSortBy
> = z.nativeEnum(ListCustomersSortBy);

/** @internal */
export const ListCustomersSortBy$outboundSchema: z.ZodNativeEnum<
  typeof ListCustomersSortBy
> = ListCustomersSortBy$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListCustomersSortBy$ {
  /** @deprecated use `ListCustomersSortBy$inboundSchema` instead. */
  export const inboundSchema = ListCustomersSortBy$inboundSchema;
  /** @deprecated use `ListCustomersSortBy$outboundSchema` instead. */
  export const outboundSchema = ListCustomersSortBy$outboundSchema;
}

/** @internal */
export const ListCustomersRequest$inboundSchema: z.ZodType<
  ListCustomersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  q: z.nullable(z.string()).optional(),
  cursor: z.nullable(z.string()).optional(),
  limit: z.number().default(10),
  start: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  end: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  sortOrder: ListCustomersSortOrder$inboundSchema.default("desc"),
  sortBy: ListCustomersSortBy$inboundSchema.default("createdAt"),
});

/** @internal */
export type ListCustomersRequest$Outbound = {
  q?: string | null | undefined;
  cursor?: string | null | undefined;
  limit: number;
  start?: string | null | undefined;
  end?: string | null | undefined;
  sortOrder: string;
  sortBy: string;
};

/** @internal */
export const ListCustomersRequest$outboundSchema: z.ZodType<
  ListCustomersRequest$Outbound,
  z.ZodTypeDef,
  ListCustomersRequest
> = z.object({
  q: z.nullable(z.string()).optional(),
  cursor: z.nullable(z.string()).optional(),
  limit: z.number().default(10),
  start: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  end: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  sortOrder: ListCustomersSortOrder$outboundSchema.default("desc"),
  sortBy: ListCustomersSortBy$outboundSchema.default("createdAt"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListCustomersRequest$ {
  /** @deprecated use `ListCustomersRequest$inboundSchema` instead. */
  export const inboundSchema = ListCustomersRequest$inboundSchema;
  /** @deprecated use `ListCustomersRequest$outboundSchema` instead. */
  export const outboundSchema = ListCustomersRequest$outboundSchema;
  /** @deprecated use `ListCustomersRequest$Outbound` instead. */
  export type Outbound = ListCustomersRequest$Outbound;
}

export function listCustomersRequestToJSON(
  listCustomersRequest: ListCustomersRequest,
): string {
  return JSON.stringify(
    ListCustomersRequest$outboundSchema.parse(listCustomersRequest),
  );
}

export function listCustomersRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListCustomersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCustomersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCustomersRequest' from JSON`,
  );
}

/** @internal */
export const ListCustomersResponse$inboundSchema: z.ZodType<
  ListCustomersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: models.CustomerListResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type ListCustomersResponse$Outbound = {
  Result: models.CustomerListResponse$Outbound;
};

/** @internal */
export const ListCustomersResponse$outboundSchema: z.ZodType<
  ListCustomersResponse$Outbound,
  z.ZodTypeDef,
  ListCustomersResponse
> = z.object({
  result: models.CustomerListResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListCustomersResponse$ {
  /** @deprecated use `ListCustomersResponse$inboundSchema` instead. */
  export const inboundSchema = ListCustomersResponse$inboundSchema;
  /** @deprecated use `ListCustomersResponse$outboundSchema` instead. */
  export const outboundSchema = ListCustomersResponse$outboundSchema;
  /** @deprecated use `ListCustomersResponse$Outbound` instead. */
  export type Outbound = ListCustomersResponse$Outbound;
}

export function listCustomersResponseToJSON(
  listCustomersResponse: ListCustomersResponse,
): string {
  return JSON.stringify(
    ListCustomersResponse$outboundSchema.parse(listCustomersResponse),
  );
}

export function listCustomersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCustomersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCustomersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCustomersResponse' from JSON`,
  );
}
