/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateRequest = {
  /**
   * Unique identifier for the customer, prefixed with 'cus_'.
   */
  id: string | null;
  customerRequest: models.CustomerRequest;
};

/** @internal */
export type UpdateRequest$Outbound = {
  id: string | null;
  CustomerRequest: models.CustomerRequest$Outbound;
};

/** @internal */
export const UpdateRequest$outboundSchema: z.ZodType<
  UpdateRequest$Outbound,
  z.ZodTypeDef,
  UpdateRequest
> = z.object({
  id: z.nullable(z.string()),
  customerRequest: models.CustomerRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    customerRequest: "CustomerRequest",
  });
});

export function updateRequestToJSON(updateRequest: UpdateRequest): string {
  return JSON.stringify(UpdateRequest$outboundSchema.parse(updateRequest));
}
