/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Customer deleted successfully
 */
export type CustomerDeleteResponse = {
  id: string | null;
};

/** @internal */
export const CustomerDeleteResponse$inboundSchema: z.ZodType<
  CustomerDeleteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.string()),
});

export function customerDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<CustomerDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerDeleteResponse' from JSON`,
  );
}
