/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Environment,
  Environment$inboundSchema,
  Environment$outboundSchema,
} from "./environment.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Metadata,
  Metadata$inboundSchema,
  Metadata$Outbound,
  Metadata$outboundSchema,
} from "./metadata.js";
import {
  Source,
  Source$inboundSchema,
  Source$outboundSchema,
} from "./source.js";

export type Customer = {
  /**
   * Unique identifier for the customer, prefixed with 'cus_'
   */
  id: string;
  object: string;
  environment: Environment;
  /**
   * The name of the customer
   */
  name: string | null;
  /**
   * The phone number of the customer
   */
  phoneNumber: string;
  /**
   * The description of the customer
   */
  description: string | null;
  /**
   * The country code of the customer
   */
  countryCode: string;
  /**
   * Whether the customer is active
   */
  isActive: boolean;
  /**
   * Whether the customer is verified
   */
  isVerified: boolean;
  /**
   * Timestamp when the customer was last active (ISO 8601 format)
   */
  lastActiveAt: string | null;
  /**
   * Timestamp when the customer made their first transaction (ISO 8601 format)
   */
  firstTransactionAt: string | null;
  /**
   * The source of the resource. Either 'api', 'dashboard', or 'checkout'
   */
  source: Source;
  /**
   * Key-value object allowing you to store additional information.
   *
   * @remarks
   *
   * **Key Requirements:**
   * - Must be a string
   * - Maximum length of 40 characters
   *
   * **Value Types:**
   * - String (maximum 500 characters)
   * - Integer
   * - Floating-point number
   * - Boolean
   *
   * **Limits:**
   * - Maximum of 50 key-value pairs
   */
  metadata: { [k: string]: Metadata };
  /**
   * Timestamp when the customer was created (ISO 8601 format)
   */
  createdAt: string;
  /**
   * Timestamp when the customer was last updated (ISO 8601 format)
   */
  updatedAt: string;
};

/** @internal */
export const Customer$inboundSchema: z.ZodType<
  Customer,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: z.string(),
  environment: Environment$inboundSchema,
  name: z.nullable(z.string()),
  phoneNumber: z.string(),
  description: z.nullable(z.string()),
  countryCode: z.string(),
  isActive: z.boolean(),
  isVerified: z.boolean(),
  lastActiveAt: z.nullable(z.string()),
  firstTransactionAt: z.nullable(z.string()),
  source: Source$inboundSchema,
  metadata: z.record(Metadata$inboundSchema),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/** @internal */
export type Customer$Outbound = {
  id: string;
  object: string;
  environment: string;
  name: string | null;
  phoneNumber: string;
  description: string | null;
  countryCode: string;
  isActive: boolean;
  isVerified: boolean;
  lastActiveAt: string | null;
  firstTransactionAt: string | null;
  source: string;
  metadata: { [k: string]: Metadata$Outbound };
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const Customer$outboundSchema: z.ZodType<
  Customer$Outbound,
  z.ZodTypeDef,
  Customer
> = z.object({
  id: z.string(),
  object: z.string(),
  environment: Environment$outboundSchema,
  name: z.nullable(z.string()),
  phoneNumber: z.string(),
  description: z.nullable(z.string()),
  countryCode: z.string(),
  isActive: z.boolean(),
  isVerified: z.boolean(),
  lastActiveAt: z.nullable(z.string()),
  firstTransactionAt: z.nullable(z.string()),
  source: Source$outboundSchema,
  metadata: z.record(Metadata$outboundSchema),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Customer$ {
  /** @deprecated use `Customer$inboundSchema` instead. */
  export const inboundSchema = Customer$inboundSchema;
  /** @deprecated use `Customer$outboundSchema` instead. */
  export const outboundSchema = Customer$outboundSchema;
  /** @deprecated use `Customer$Outbound` instead. */
  export type Outbound = Customer$Outbound;
}

export function customerToJSON(customer: Customer): string {
  return JSON.stringify(Customer$outboundSchema.parse(customer));
}

export function customerFromJSON(
  jsonString: string,
): SafeParseResult<Customer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Customer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Customer' from JSON`,
  );
}
