/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Customer, Customer$inboundSchema } from "./customer.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CustomerListResponseMeta = {
  /**
   * Cursor for pagination, representing the last item from the previous page
   */
  cursor: string | null;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
};

/**
 * List of all customers
 */
export type CustomerListResponse = {
  data: Array<Customer>;
  meta: CustomerListResponseMeta;
};

/** @internal */
export const CustomerListResponseMeta$inboundSchema: z.ZodType<
  CustomerListResponseMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.nullable(z.string()),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});

export function customerListResponseMetaFromJSON(
  jsonString: string,
): SafeParseResult<CustomerListResponseMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerListResponseMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerListResponseMeta' from JSON`,
  );
}

/** @internal */
export const CustomerListResponse$inboundSchema: z.ZodType<
  CustomerListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Customer$inboundSchema),
  meta: z.lazy(() => CustomerListResponseMeta$inboundSchema),
});

export function customerListResponseFromJSON(
  jsonString: string,
): SafeParseResult<CustomerListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerListResponse' from JSON`,
  );
}
