/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Customer deleted successfully
 */
export type CustomerDeleteResponse = {
  id: string | null;
};

/** @internal */
export const CustomerDeleteResponse$inboundSchema: z.ZodType<
  CustomerDeleteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.string()),
});

/** @internal */
export type CustomerDeleteResponse$Outbound = {
  id: string | null;
};

/** @internal */
export const CustomerDeleteResponse$outboundSchema: z.ZodType<
  CustomerDeleteResponse$Outbound,
  z.ZodTypeDef,
  CustomerDeleteResponse
> = z.object({
  id: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomerDeleteResponse$ {
  /** @deprecated use `CustomerDeleteResponse$inboundSchema` instead. */
  export const inboundSchema = CustomerDeleteResponse$inboundSchema;
  /** @deprecated use `CustomerDeleteResponse$outboundSchema` instead. */
  export const outboundSchema = CustomerDeleteResponse$outboundSchema;
  /** @deprecated use `CustomerDeleteResponse$Outbound` instead. */
  export type Outbound = CustomerDeleteResponse$Outbound;
}

export function customerDeleteResponseToJSON(
  customerDeleteResponse: CustomerDeleteResponse,
): string {
  return JSON.stringify(
    CustomerDeleteResponse$outboundSchema.parse(customerDeleteResponse),
  );
}

export function customerDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<CustomerDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerDeleteResponse' from JSON`,
  );
}
