/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Metadata,
  Metadata$inboundSchema,
  Metadata$Outbound,
  Metadata$outboundSchema,
} from "./metadata.js";

export type CustomerRequest = {
  name?: string | undefined;
  /**
   * The phone number of the customer
   */
  phoneNumber: string;
  description?: string | undefined;
  /**
   * Key-value object allowing you to store additional information.
   *
   * @remarks
   *
   * **Key Requirements:**
   * - Must be a string
   * - Maximum length of 40 characters
   *
   * **Value Types:**
   * - String (maximum 500 characters)
   * - Integer
   * - Floating-point number
   * - Boolean
   *
   * **Limits:**
   * - Maximum of 50 key-value pairs
   */
  metadata?: { [k: string]: Metadata } | undefined;
};

/** @internal */
export const CustomerRequest$inboundSchema: z.ZodType<
  CustomerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  phoneNumber: z.string(),
  description: z.string().optional(),
  metadata: z.record(Metadata$inboundSchema).optional(),
});

/** @internal */
export type CustomerRequest$Outbound = {
  name?: string | undefined;
  phoneNumber: string;
  description?: string | undefined;
  metadata?: { [k: string]: Metadata$Outbound } | undefined;
};

/** @internal */
export const CustomerRequest$outboundSchema: z.ZodType<
  CustomerRequest$Outbound,
  z.ZodTypeDef,
  CustomerRequest
> = z.object({
  name: z.string().optional(),
  phoneNumber: z.string(),
  description: z.string().optional(),
  metadata: z.record(Metadata$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomerRequest$ {
  /** @deprecated use `CustomerRequest$inboundSchema` instead. */
  export const inboundSchema = CustomerRequest$inboundSchema;
  /** @deprecated use `CustomerRequest$outboundSchema` instead. */
  export const outboundSchema = CustomerRequest$outboundSchema;
  /** @deprecated use `CustomerRequest$Outbound` instead. */
  export type Outbound = CustomerRequest$Outbound;
}

export function customerRequestToJSON(
  customerRequest: CustomerRequest,
): string {
  return JSON.stringify(CustomerRequest$outboundSchema.parse(customerRequest));
}

export function customerRequestFromJSON(
  jsonString: string,
): SafeParseResult<CustomerRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerRequest' from JSON`,
  );
}
