/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  Metadata,
  Metadata$Outbound,
  Metadata$outboundSchema,
} from "./metadata.js";

export type CustomerRequest = {
  name?: string | undefined;
  /**
   * The phone number of the customer
   */
  phoneNumber: string;
  description?: string | undefined;
  /**
   * Key-value object allowing you to store additional information.
   *
   * @remarks
   *
   * **Key Requirements:**
   * - Must be a string
   * - Maximum length of 40 characters
   *
   * **Value Types:**
   * - String (maximum 500 characters)
   * - Integer
   * - Floating-point number
   * - Boolean
   *
   * **Limits:**
   * - Maximum of 50 key-value pairs
   */
  metadata?: { [k: string]: Metadata } | undefined;
};

/** @internal */
export type CustomerRequest$Outbound = {
  name?: string | undefined;
  phoneNumber: string;
  description?: string | undefined;
  metadata?: { [k: string]: Metadata$Outbound } | undefined;
};

/** @internal */
export const CustomerRequest$outboundSchema: z.ZodType<
  CustomerRequest$Outbound,
  z.ZodTypeDef,
  CustomerRequest
> = z.object({
  name: z.string().optional(),
  phoneNumber: z.string(),
  description: z.string().optional(),
  metadata: z.record(Metadata$outboundSchema).optional(),
});

export function customerRequestToJSON(
  customerRequest: CustomerRequest,
): string {
  return JSON.stringify(CustomerRequest$outboundSchema.parse(customerRequest));
}
