/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Customer,
  Customer$inboundSchema,
  Customer$Outbound,
  Customer$outboundSchema,
} from "./customer.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CustomerListResponseMeta = {
  /**
   * Cursor for pagination, representing the last item from the previous page
   */
  cursor: string | null;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
};

/**
 * List of all customers
 */
export type CustomerListResponse = {
  data: Array<Customer>;
  meta: CustomerListResponseMeta;
};

/** @internal */
export const CustomerListResponseMeta$inboundSchema: z.ZodType<
  CustomerListResponseMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.nullable(z.string()),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});

/** @internal */
export type CustomerListResponseMeta$Outbound = {
  cursor: string | null;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
};

/** @internal */
export const CustomerListResponseMeta$outboundSchema: z.ZodType<
  CustomerListResponseMeta$Outbound,
  z.ZodTypeDef,
  CustomerListResponseMeta
> = z.object({
  cursor: z.nullable(z.string()),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomerListResponseMeta$ {
  /** @deprecated use `CustomerListResponseMeta$inboundSchema` instead. */
  export const inboundSchema = CustomerListResponseMeta$inboundSchema;
  /** @deprecated use `CustomerListResponseMeta$outboundSchema` instead. */
  export const outboundSchema = CustomerListResponseMeta$outboundSchema;
  /** @deprecated use `CustomerListResponseMeta$Outbound` instead. */
  export type Outbound = CustomerListResponseMeta$Outbound;
}

export function customerListResponseMetaToJSON(
  customerListResponseMeta: CustomerListResponseMeta,
): string {
  return JSON.stringify(
    CustomerListResponseMeta$outboundSchema.parse(customerListResponseMeta),
  );
}

export function customerListResponseMetaFromJSON(
  jsonString: string,
): SafeParseResult<CustomerListResponseMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerListResponseMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerListResponseMeta' from JSON`,
  );
}

/** @internal */
export const CustomerListResponse$inboundSchema: z.ZodType<
  CustomerListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Customer$inboundSchema),
  meta: z.lazy(() => CustomerListResponseMeta$inboundSchema),
});

/** @internal */
export type CustomerListResponse$Outbound = {
  data: Array<Customer$Outbound>;
  meta: CustomerListResponseMeta$Outbound;
};

/** @internal */
export const CustomerListResponse$outboundSchema: z.ZodType<
  CustomerListResponse$Outbound,
  z.ZodTypeDef,
  CustomerListResponse
> = z.object({
  data: z.array(Customer$outboundSchema),
  meta: z.lazy(() => CustomerListResponseMeta$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomerListResponse$ {
  /** @deprecated use `CustomerListResponse$inboundSchema` instead. */
  export const inboundSchema = CustomerListResponse$inboundSchema;
  /** @deprecated use `CustomerListResponse$outboundSchema` instead. */
  export const outboundSchema = CustomerListResponse$outboundSchema;
  /** @deprecated use `CustomerListResponse$Outbound` instead. */
  export type Outbound = CustomerListResponse$Outbound;
}

export function customerListResponseToJSON(
  customerListResponse: CustomerListResponse,
): string {
  return JSON.stringify(
    CustomerListResponse$outboundSchema.parse(customerListResponse),
  );
}

export function customerListResponseFromJSON(
  jsonString: string,
): SafeParseResult<CustomerListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerListResponse' from JSON`,
  );
}
