/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Initial payment status after the STK Push request is accepted
 */
export const Status = {
  Pending: "pending",
} as const;
/**
 * Initial payment status after the STK Push request is accepted
 */
export type Status = ClosedEnum<typeof Status>;

/**
 * Environment where the payment was created. Either 'sandbox' or 'production'
 */
export const DarajaExpressResponseEnvironment = {
  Sandbox: "sandbox",
  Production: "production",
} as const;
/**
 * Environment where the payment was created. Either 'sandbox' or 'production'
 */
export type DarajaExpressResponseEnvironment = ClosedEnum<
  typeof DarajaExpressResponseEnvironment
>;

/**
 * Payment Response
 */
export type DarajaExpressResponse = {
  /**
   * Unique identifier for the payment, prefixed with 'pay_'
   */
  paymentId: string;
  /**
   * Unique identifier for the related transaction, prefixed with 'trxn_'
   */
  transactionId: string;
  /**
   * Unique identifier for the customer attached to the payment, prefixed with 'cus_'
   */
  customerId: string;
  /**
   * Customer Safaricom phone number that received the M-Pesa STK Push
   */
  phoneNumber: string;
  /**
   * Payment amount in the smallest currency unit
   */
  amount: number;
  /**
   * Three-letter ISO currency code for the payment
   */
  currency: string;
  /**
   * Initial payment status after the STK Push request is accepted
   */
  status: Status;
  /**
   * Short customer-facing payment description
   */
  description: string;
  /**
   * Short alphanumeric reference that was sent to M-Pesa and stored with this payment, such as an order or invoice number.
   */
  accountReference: string;
  /**
   * Environment where the payment was created. Either 'sandbox' or 'production'
   */
  environment: DarajaExpressResponseEnvironment;
  /**
   * Timestamp when the payment request was accepted (ISO 8601 format)
   */
  timestamp: Date;
  /**
   * Human-readable message describing the initiation result
   */
  message: string;
};

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export const Status$outboundSchema: z.ZodNativeEnum<typeof Status> =
  Status$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Status$ {
  /** @deprecated use `Status$inboundSchema` instead. */
  export const inboundSchema = Status$inboundSchema;
  /** @deprecated use `Status$outboundSchema` instead. */
  export const outboundSchema = Status$outboundSchema;
}

/** @internal */
export const DarajaExpressResponseEnvironment$inboundSchema: z.ZodNativeEnum<
  typeof DarajaExpressResponseEnvironment
> = z.nativeEnum(DarajaExpressResponseEnvironment);

/** @internal */
export const DarajaExpressResponseEnvironment$outboundSchema: z.ZodNativeEnum<
  typeof DarajaExpressResponseEnvironment
> = DarajaExpressResponseEnvironment$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DarajaExpressResponseEnvironment$ {
  /** @deprecated use `DarajaExpressResponseEnvironment$inboundSchema` instead. */
  export const inboundSchema = DarajaExpressResponseEnvironment$inboundSchema;
  /** @deprecated use `DarajaExpressResponseEnvironment$outboundSchema` instead. */
  export const outboundSchema = DarajaExpressResponseEnvironment$outboundSchema;
}

/** @internal */
export const DarajaExpressResponse$inboundSchema: z.ZodType<
  DarajaExpressResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  paymentId: z.string(),
  transactionId: z.string(),
  customerId: z.string(),
  phoneNumber: z.string(),
  amount: z.number(),
  currency: z.string(),
  status: Status$inboundSchema,
  description: z.string(),
  accountReference: z.string(),
  environment: DarajaExpressResponseEnvironment$inboundSchema,
  timestamp: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  message: z.string(),
});

/** @internal */
export type DarajaExpressResponse$Outbound = {
  paymentId: string;
  transactionId: string;
  customerId: string;
  phoneNumber: string;
  amount: number;
  currency: string;
  status: string;
  description: string;
  accountReference: string;
  environment: string;
  timestamp: string;
  message: string;
};

/** @internal */
export const DarajaExpressResponse$outboundSchema: z.ZodType<
  DarajaExpressResponse$Outbound,
  z.ZodTypeDef,
  DarajaExpressResponse
> = z.object({
  paymentId: z.string(),
  transactionId: z.string(),
  customerId: z.string(),
  phoneNumber: z.string(),
  amount: z.number(),
  currency: z.string(),
  status: Status$outboundSchema,
  description: z.string(),
  accountReference: z.string(),
  environment: DarajaExpressResponseEnvironment$outboundSchema,
  timestamp: z.date().transform(v => v.toISOString()),
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DarajaExpressResponse$ {
  /** @deprecated use `DarajaExpressResponse$inboundSchema` instead. */
  export const inboundSchema = DarajaExpressResponse$inboundSchema;
  /** @deprecated use `DarajaExpressResponse$outboundSchema` instead. */
  export const outboundSchema = DarajaExpressResponse$outboundSchema;
  /** @deprecated use `DarajaExpressResponse$Outbound` instead. */
  export type Outbound = DarajaExpressResponse$Outbound;
}

export function darajaExpressResponseToJSON(
  darajaExpressResponse: DarajaExpressResponse,
): string {
  return JSON.stringify(
    DarajaExpressResponse$outboundSchema.parse(darajaExpressResponse),
  );
}

export function darajaExpressResponseFromJSON(
  jsonString: string,
): SafeParseResult<DarajaExpressResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DarajaExpressResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DarajaExpressResponse' from JSON`,
  );
}
