/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DuplicateErrorError = {
  /**
   * HTTP status code of the error
   */
  status: number;
  /**
   * Machine-readable error name
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
};

/** @internal */
export const DuplicateErrorError$inboundSchema: z.ZodType<
  DuplicateErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
});

export function duplicateErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<DuplicateErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DuplicateErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DuplicateErrorError' from JSON`,
  );
}
