/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DuplicateErrorError = {
  /**
   * HTTP status code of the error
   */
  status: number;
  /**
   * Machine-readable error name
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
};

/** @internal */
export const DuplicateErrorError$inboundSchema: z.ZodType<
  DuplicateErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
});

/** @internal */
export type DuplicateErrorError$Outbound = {
  status: number;
  code: string;
  message: string;
};

/** @internal */
export const DuplicateErrorError$outboundSchema: z.ZodType<
  DuplicateErrorError$Outbound,
  z.ZodTypeDef,
  DuplicateErrorError
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DuplicateErrorError$ {
  /** @deprecated use `DuplicateErrorError$inboundSchema` instead. */
  export const inboundSchema = DuplicateErrorError$inboundSchema;
  /** @deprecated use `DuplicateErrorError$outboundSchema` instead. */
  export const outboundSchema = DuplicateErrorError$outboundSchema;
  /** @deprecated use `DuplicateErrorError$Outbound` instead. */
  export type Outbound = DuplicateErrorError$Outbound;
}

export function duplicateErrorErrorToJSON(
  duplicateErrorError: DuplicateErrorError,
): string {
  return JSON.stringify(
    DuplicateErrorError$outboundSchema.parse(duplicateErrorError),
  );
}

export function duplicateErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<DuplicateErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DuplicateErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DuplicateErrorError' from JSON`,
  );
}
