/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * The environment of the customer. Either 'sandbox' or 'production'
 */
export const Environment = {
  Sandbox: "sandbox",
  Production: "production",
} as const;
/**
 * The environment of the customer. Either 'sandbox' or 'production'
 */
export type Environment = ClosedEnum<typeof Environment>;

/** @internal */
export const Environment$inboundSchema: z.ZodNativeEnum<typeof Environment> = z
  .nativeEnum(Environment);
