/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type InternalServerErrorError = {
  /**
   * HTTP status code of the error
   */
  status: number;
  /**
   * Machine-readable error name
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
};

/** @internal */
export const InternalServerErrorError$inboundSchema: z.ZodType<
  InternalServerErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
});

/** @internal */
export type InternalServerErrorError$Outbound = {
  status: number;
  code: string;
  message: string;
};

/** @internal */
export const InternalServerErrorError$outboundSchema: z.ZodType<
  InternalServerErrorError$Outbound,
  z.ZodTypeDef,
  InternalServerErrorError
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InternalServerErrorError$ {
  /** @deprecated use `InternalServerErrorError$inboundSchema` instead. */
  export const inboundSchema = InternalServerErrorError$inboundSchema;
  /** @deprecated use `InternalServerErrorError$outboundSchema` instead. */
  export const outboundSchema = InternalServerErrorError$outboundSchema;
  /** @deprecated use `InternalServerErrorError$Outbound` instead. */
  export type Outbound = InternalServerErrorError$Outbound;
}

export function internalServerErrorErrorToJSON(
  internalServerErrorError: InternalServerErrorError,
): string {
  return JSON.stringify(
    InternalServerErrorError$outboundSchema.parse(internalServerErrorError),
  );
}

export function internalServerErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<InternalServerErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InternalServerErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InternalServerErrorError' from JSON`,
  );
}
