/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type InvalidAccessErrorError = {
  /**
   * HTTP status code of the error
   */
  status: number;
};

/** @internal */
export const InvalidAccessErrorError$inboundSchema: z.ZodType<
  InvalidAccessErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number(),
});

export function invalidAccessErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<InvalidAccessErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvalidAccessErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvalidAccessErrorError' from JSON`,
  );
}
