/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type InvalidAccessErrorError = {
  /**
   * HTTP status code of the error
   */
  status: number;
};

/** @internal */
export const InvalidAccessErrorError$inboundSchema: z.ZodType<
  InvalidAccessErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number(),
});

/** @internal */
export type InvalidAccessErrorError$Outbound = {
  status: number;
};

/** @internal */
export const InvalidAccessErrorError$outboundSchema: z.ZodType<
  InvalidAccessErrorError$Outbound,
  z.ZodTypeDef,
  InvalidAccessErrorError
> = z.object({
  status: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InvalidAccessErrorError$ {
  /** @deprecated use `InvalidAccessErrorError$inboundSchema` instead. */
  export const inboundSchema = InvalidAccessErrorError$inboundSchema;
  /** @deprecated use `InvalidAccessErrorError$outboundSchema` instead. */
  export const outboundSchema = InvalidAccessErrorError$outboundSchema;
  /** @deprecated use `InvalidAccessErrorError$Outbound` instead. */
  export type Outbound = InvalidAccessErrorError$Outbound;
}

export function invalidAccessErrorErrorToJSON(
  invalidAccessErrorError: InvalidAccessErrorError,
): string {
  return JSON.stringify(
    InvalidAccessErrorError$outboundSchema.parse(invalidAccessErrorError),
  );
}

export function invalidAccessErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<InvalidAccessErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvalidAccessErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvalidAccessErrorError' from JSON`,
  );
}
