/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type MethodNotAllowedErrorError = {
  /**
   * HTTP status code of the error
   */
  status: number;
  /**
   * Machine-readable error name
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
};

/** @internal */
export const MethodNotAllowedErrorError$inboundSchema: z.ZodType<
  MethodNotAllowedErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
});

/** @internal */
export type MethodNotAllowedErrorError$Outbound = {
  status: number;
  code: string;
  message: string;
};

/** @internal */
export const MethodNotAllowedErrorError$outboundSchema: z.ZodType<
  MethodNotAllowedErrorError$Outbound,
  z.ZodTypeDef,
  MethodNotAllowedErrorError
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MethodNotAllowedErrorError$ {
  /** @deprecated use `MethodNotAllowedErrorError$inboundSchema` instead. */
  export const inboundSchema = MethodNotAllowedErrorError$inboundSchema;
  /** @deprecated use `MethodNotAllowedErrorError$outboundSchema` instead. */
  export const outboundSchema = MethodNotAllowedErrorError$outboundSchema;
  /** @deprecated use `MethodNotAllowedErrorError$Outbound` instead. */
  export type Outbound = MethodNotAllowedErrorError$Outbound;
}

export function methodNotAllowedErrorErrorToJSON(
  methodNotAllowedErrorError: MethodNotAllowedErrorError,
): string {
  return JSON.stringify(
    MethodNotAllowedErrorError$outboundSchema.parse(methodNotAllowedErrorError),
  );
}

export function methodNotAllowedErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<MethodNotAllowedErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MethodNotAllowedErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MethodNotAllowedErrorError' from JSON`,
  );
}
