/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type MissingApiKeyErrorError = {
  /**
   * HTTP status code of the error
   */
  status: number;
  /**
   * Machine-readable error name
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
};

/** @internal */
export const MissingApiKeyErrorError$inboundSchema: z.ZodType<
  MissingApiKeyErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
});

/** @internal */
export type MissingApiKeyErrorError$Outbound = {
  status: number;
  code: string;
  message: string;
};

/** @internal */
export const MissingApiKeyErrorError$outboundSchema: z.ZodType<
  MissingApiKeyErrorError$Outbound,
  z.ZodTypeDef,
  MissingApiKeyErrorError
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MissingApiKeyErrorError$ {
  /** @deprecated use `MissingApiKeyErrorError$inboundSchema` instead. */
  export const inboundSchema = MissingApiKeyErrorError$inboundSchema;
  /** @deprecated use `MissingApiKeyErrorError$outboundSchema` instead. */
  export const outboundSchema = MissingApiKeyErrorError$outboundSchema;
  /** @deprecated use `MissingApiKeyErrorError$Outbound` instead. */
  export type Outbound = MissingApiKeyErrorError$Outbound;
}

export function missingApiKeyErrorErrorToJSON(
  missingApiKeyErrorError: MissingApiKeyErrorError,
): string {
  return JSON.stringify(
    MissingApiKeyErrorError$outboundSchema.parse(missingApiKeyErrorError),
  );
}

export function missingApiKeyErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<MissingApiKeyErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MissingApiKeyErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MissingApiKeyErrorError' from JSON`,
  );
}
