/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type NotFoundErrorError = {
  /**
   * HTTP status code of the error
   */
  status: number;
  /**
   * Machine-readable error name
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
};

/** @internal */
export const NotFoundErrorError$inboundSchema: z.ZodType<
  NotFoundErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
});

/** @internal */
export type NotFoundErrorError$Outbound = {
  status: number;
  code: string;
  message: string;
};

/** @internal */
export const NotFoundErrorError$outboundSchema: z.ZodType<
  NotFoundErrorError$Outbound,
  z.ZodTypeDef,
  NotFoundErrorError
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotFoundErrorError$ {
  /** @deprecated use `NotFoundErrorError$inboundSchema` instead. */
  export const inboundSchema = NotFoundErrorError$inboundSchema;
  /** @deprecated use `NotFoundErrorError$outboundSchema` instead. */
  export const outboundSchema = NotFoundErrorError$outboundSchema;
  /** @deprecated use `NotFoundErrorError$Outbound` instead. */
  export type Outbound = NotFoundErrorError$Outbound;
}

export function notFoundErrorErrorToJSON(
  notFoundErrorError: NotFoundErrorError,
): string {
  return JSON.stringify(
    NotFoundErrorError$outboundSchema.parse(notFoundErrorError),
  );
}

export function notFoundErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<NotFoundErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NotFoundErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NotFoundErrorError' from JSON`,
  );
}
