/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  TransactionStatus,
  TransactionStatus$inboundSchema,
  TransactionStatus$outboundSchema,
} from "./transactionstatus.js";

/**
 * Environment where the payment was created. Either 'sandbox' or 'production'
 */
export const PaymentStatusEnvironment = {
  Sandbox: "sandbox",
  Production: "production",
} as const;
/**
 * Environment where the payment was created. Either 'sandbox' or 'production'
 */
export type PaymentStatusEnvironment = ClosedEnum<
  typeof PaymentStatusEnvironment
>;

/**
 * Payment Status
 */
export type PaymentStatus = {
  /**
   * Unique identifier for the payment, prefixed with 'pay_'
   */
  id: string;
  /**
   * Unique identifier for the related transaction, prefixed with 'trxn_'
   */
  transactionId: string;
  /**
   * Unique identifier for the customer attached to the payment, prefixed with 'cus_'
   */
  customerId: string | null;
  /**
   * M-Pesa MerchantRequestID returned by Safaricom
   */
  merchantRequestId: string | null;
  /**
   * M-Pesa CheckoutRequestID used to reconcile the STK push
   */
  checkoutRequestId: string | null;
  /**
   * Current status. Possible values: initiating, pending, completed, failed, unknown
   */
  status: TransactionStatus;
  /**
   * Provider detail explaining the current payment status, when available
   */
  statusDetail: string | null;
  /**
   * Payment amount in the smallest currency unit
   */
  amount: number;
  /**
   * Three-letter ISO currency code for the payment
   */
  currency: string;
  /**
   * Short customer-facing payment description
   */
  description: string;
  /**
   * Short alphanumeric reference that was sent to M-Pesa and stored with this payment, such as an order or invoice number.
   */
  accountReference: string;
  /**
   * M-Pesa receipt number for a completed payment
   */
  receiptNumber: string | null;
  /**
   * Environment where the payment was created. Either 'sandbox' or 'production'
   */
  environment: PaymentStatusEnvironment;
  /**
   * Timestamp when the payment was created (ISO 8601 format)
   */
  createdAt: Date;
  /**
   * Timestamp when the payment was last updated (ISO 8601 format)
   */
  updatedAt: Date;
  /**
   * Timestamp when the payment completed successfully (ISO 8601 format)
   */
  completedAt: Date | null;
  /**
   * Timestamp when the payment failed (ISO 8601 format)
   */
  failedAt: Date | null;
  /**
   * Timestamp when the payment moved to an unknown state (ISO 8601 format)
   */
  unknownAt: Date | null;
};

/** @internal */
export const PaymentStatusEnvironment$inboundSchema: z.ZodNativeEnum<
  typeof PaymentStatusEnvironment
> = z.nativeEnum(PaymentStatusEnvironment);

/** @internal */
export const PaymentStatusEnvironment$outboundSchema: z.ZodNativeEnum<
  typeof PaymentStatusEnvironment
> = PaymentStatusEnvironment$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentStatusEnvironment$ {
  /** @deprecated use `PaymentStatusEnvironment$inboundSchema` instead. */
  export const inboundSchema = PaymentStatusEnvironment$inboundSchema;
  /** @deprecated use `PaymentStatusEnvironment$outboundSchema` instead. */
  export const outboundSchema = PaymentStatusEnvironment$outboundSchema;
}

/** @internal */
export const PaymentStatus$inboundSchema: z.ZodType<
  PaymentStatus,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  transactionId: z.string(),
  customerId: z.nullable(z.string()),
  merchantRequestId: z.nullable(z.string()),
  checkoutRequestId: z.nullable(z.string()),
  status: TransactionStatus$inboundSchema,
  statusDetail: z.nullable(z.string()),
  amount: z.number(),
  currency: z.string(),
  description: z.string(),
  accountReference: z.string(),
  receiptNumber: z.nullable(z.string()),
  environment: PaymentStatusEnvironment$inboundSchema,
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  completedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  failedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  unknownAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
});

/** @internal */
export type PaymentStatus$Outbound = {
  id: string;
  transactionId: string;
  customerId: string | null;
  merchantRequestId: string | null;
  checkoutRequestId: string | null;
  status: string;
  statusDetail: string | null;
  amount: number;
  currency: string;
  description: string;
  accountReference: string;
  receiptNumber: string | null;
  environment: string;
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
  failedAt: string | null;
  unknownAt: string | null;
};

/** @internal */
export const PaymentStatus$outboundSchema: z.ZodType<
  PaymentStatus$Outbound,
  z.ZodTypeDef,
  PaymentStatus
> = z.object({
  id: z.string(),
  transactionId: z.string(),
  customerId: z.nullable(z.string()),
  merchantRequestId: z.nullable(z.string()),
  checkoutRequestId: z.nullable(z.string()),
  status: TransactionStatus$outboundSchema,
  statusDetail: z.nullable(z.string()),
  amount: z.number(),
  currency: z.string(),
  description: z.string(),
  accountReference: z.string(),
  receiptNumber: z.nullable(z.string()),
  environment: PaymentStatusEnvironment$outboundSchema,
  createdAt: z.date().transform(v => v.toISOString()),
  updatedAt: z.date().transform(v => v.toISOString()),
  completedAt: z.nullable(z.date().transform(v => v.toISOString())),
  failedAt: z.nullable(z.date().transform(v => v.toISOString())),
  unknownAt: z.nullable(z.date().transform(v => v.toISOString())),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentStatus$ {
  /** @deprecated use `PaymentStatus$inboundSchema` instead. */
  export const inboundSchema = PaymentStatus$inboundSchema;
  /** @deprecated use `PaymentStatus$outboundSchema` instead. */
  export const outboundSchema = PaymentStatus$outboundSchema;
  /** @deprecated use `PaymentStatus$Outbound` instead. */
  export type Outbound = PaymentStatus$Outbound;
}

export function paymentStatusToJSON(paymentStatus: PaymentStatus): string {
  return JSON.stringify(PaymentStatus$outboundSchema.parse(paymentStatus));
}

export function paymentStatusFromJSON(
  jsonString: string,
): SafeParseResult<PaymentStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentStatus' from JSON`,
  );
}
