/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type RateLimitExceededErrorError = {
  /**
   * HTTP status code of the error
   */
  status: number;
  /**
   * Machine-readable error name
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
};

/** @internal */
export const RateLimitExceededErrorError$inboundSchema: z.ZodType<
  RateLimitExceededErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
});

/** @internal */
export type RateLimitExceededErrorError$Outbound = {
  status: number;
  code: string;
  message: string;
};

/** @internal */
export const RateLimitExceededErrorError$outboundSchema: z.ZodType<
  RateLimitExceededErrorError$Outbound,
  z.ZodTypeDef,
  RateLimitExceededErrorError
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RateLimitExceededErrorError$ {
  /** @deprecated use `RateLimitExceededErrorError$inboundSchema` instead. */
  export const inboundSchema = RateLimitExceededErrorError$inboundSchema;
  /** @deprecated use `RateLimitExceededErrorError$outboundSchema` instead. */
  export const outboundSchema = RateLimitExceededErrorError$outboundSchema;
  /** @deprecated use `RateLimitExceededErrorError$Outbound` instead. */
  export type Outbound = RateLimitExceededErrorError$Outbound;
}

export function rateLimitExceededErrorErrorToJSON(
  rateLimitExceededErrorError: RateLimitExceededErrorError,
): string {
  return JSON.stringify(
    RateLimitExceededErrorError$outboundSchema.parse(
      rateLimitExceededErrorError,
    ),
  );
}

export function rateLimitExceededErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<RateLimitExceededErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RateLimitExceededErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RateLimitExceededErrorError' from JSON`,
  );
}
