/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * The source of the resource. Either 'api', 'dashboard', or 'checkout'
 */
export const Source = {
  Api: "api",
  Dashboard: "dashboard",
  Checkout: "checkout",
} as const;
/**
 * The source of the resource. Either 'api', 'dashboard', or 'checkout'
 */
export type Source = ClosedEnum<typeof Source>;

/** @internal */
export const Source$inboundSchema: z.ZodNativeEnum<typeof Source> = z
  .nativeEnum(Source);
