/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Environment, Environment$inboundSchema } from "./environment.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Metadata, Metadata$inboundSchema } from "./metadata.js";
import { Source, Source$inboundSchema } from "./source.js";
import {
  TransactionStatus,
  TransactionStatus$inboundSchema,
} from "./transactionstatus.js";

/**
 * The type of transaction
 */
export const TransactionType = {
  Payment: "payment",
} as const;
/**
 * The type of transaction
 */
export type TransactionType = ClosedEnum<typeof TransactionType>;

export type Transaction = {
  /**
   * Unique identifier for the transaction, prefixed with 'trxn_'
   */
  id: string;
  /**
   * Unique identifier for the customer, prefixed with 'cus_'
   */
  customerId: string | null;
  object: string;
  /**
   * The environment of the transaction. Either 'sandbox' or 'production'
   */
  environment: Environment;
  /**
   * The transaction currency
   */
  currency: string;
  /**
   * Transaction amount in cents (e.g., 1000 = KES 10.00)
   */
  amount: number;
  /**
   * Human-readable description of the transaction purpose
   */
  description: string;
  /**
   * Safaricom phone number in local (e.g., 0712345678, 0110123456) or international (e.g., 254712345678, 254110123456) format, transformed to 254XXXXXXXXX for M-PESA STK Push. Supports all Safaricom prefixes (070X, 074X, 0757–0759, 0768–0769, 079X, 0110–0117).
   */
  phoneNumber: string;
  /**
   * Current status. Possible values: initiating, pending, completed, failed, canceled, unknown
   */
  status: TransactionStatus;
  /**
   * The type of transaction
   */
  type: TransactionType;
  /**
   * The M-Pesa receipt number
   */
  receiptNumber: string | null;
  /**
   * Timestamp when the transaction was processed (ISO 8601 format)
   */
  processedAt: string | null;
  /**
   * Timestamp when the transaction was successfully paid (ISO 8601 format)
   */
  paidAt: string | null;
  /**
   * Timestamp when the transaction failed (ISO 8601 format)
   */
  failedAt: string | null;
  /**
   * Timestamp when the transaction moved to an unknown state (ISO 8601 format)
   */
  unknownAt: string | null;
  /**
   * The transaction decline reason
   */
  failureReason: string | null;
  /**
   * Key-value object allowing you to store additional information.
   *
   * @remarks
   *
   * **Key Requirements:**
   * - Must be a string
   * - Maximum length of 40 characters
   *
   * **Value Types:**
   * - String (maximum 500 characters)
   * - Integer
   * - Floating-point number
   * - Boolean
   *
   * **Limits:**
   * - Maximum of 50 key-value pairs
   */
  metadata: { [k: string]: Metadata };
  /**
   * Timestamp when the transaction was created (ISO 8601 format)
   */
  createdAt: string;
  /**
   * The source of the resource. Either 'api', 'dashboard', or 'checkout'
   */
  source: Source;
};

/** @internal */
export const TransactionType$inboundSchema: z.ZodNativeEnum<
  typeof TransactionType
> = z.nativeEnum(TransactionType);

/** @internal */
export const Transaction$inboundSchema: z.ZodType<
  Transaction,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  customerId: z.nullable(z.string()),
  object: z.string(),
  environment: Environment$inboundSchema,
  currency: z.string(),
  amount: z.number(),
  description: z.string(),
  phoneNumber: z.string(),
  status: TransactionStatus$inboundSchema,
  type: TransactionType$inboundSchema,
  receiptNumber: z.nullable(z.string()),
  processedAt: z.nullable(z.string()),
  paidAt: z.nullable(z.string()),
  failedAt: z.nullable(z.string()),
  unknownAt: z.nullable(z.string()),
  failureReason: z.nullable(z.string()),
  metadata: z.record(Metadata$inboundSchema),
  createdAt: z.string(),
  source: Source$inboundSchema,
});

export function transactionFromJSON(
  jsonString: string,
): SafeParseResult<Transaction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Transaction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Transaction' from JSON`,
  );
}
