/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Transaction,
  Transaction$inboundSchema,
  Transaction$Outbound,
  Transaction$outboundSchema,
} from "./transaction.js";

export type TransactionListResponseMeta = {
  /**
   * Cursor for pagination, representing the last item from the previous page
   */
  cursor: string | null;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
};

/**
 * List of all transactions
 */
export type TransactionListResponse = {
  data: Array<Transaction>;
  meta: TransactionListResponseMeta;
};

/** @internal */
export const TransactionListResponseMeta$inboundSchema: z.ZodType<
  TransactionListResponseMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.nullable(z.string()),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});

/** @internal */
export type TransactionListResponseMeta$Outbound = {
  cursor: string | null;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
};

/** @internal */
export const TransactionListResponseMeta$outboundSchema: z.ZodType<
  TransactionListResponseMeta$Outbound,
  z.ZodTypeDef,
  TransactionListResponseMeta
> = z.object({
  cursor: z.nullable(z.string()),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransactionListResponseMeta$ {
  /** @deprecated use `TransactionListResponseMeta$inboundSchema` instead. */
  export const inboundSchema = TransactionListResponseMeta$inboundSchema;
  /** @deprecated use `TransactionListResponseMeta$outboundSchema` instead. */
  export const outboundSchema = TransactionListResponseMeta$outboundSchema;
  /** @deprecated use `TransactionListResponseMeta$Outbound` instead. */
  export type Outbound = TransactionListResponseMeta$Outbound;
}

export function transactionListResponseMetaToJSON(
  transactionListResponseMeta: TransactionListResponseMeta,
): string {
  return JSON.stringify(
    TransactionListResponseMeta$outboundSchema.parse(
      transactionListResponseMeta,
    ),
  );
}

export function transactionListResponseMetaFromJSON(
  jsonString: string,
): SafeParseResult<TransactionListResponseMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionListResponseMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionListResponseMeta' from JSON`,
  );
}

/** @internal */
export const TransactionListResponse$inboundSchema: z.ZodType<
  TransactionListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Transaction$inboundSchema),
  meta: z.lazy(() => TransactionListResponseMeta$inboundSchema),
});

/** @internal */
export type TransactionListResponse$Outbound = {
  data: Array<Transaction$Outbound>;
  meta: TransactionListResponseMeta$Outbound;
};

/** @internal */
export const TransactionListResponse$outboundSchema: z.ZodType<
  TransactionListResponse$Outbound,
  z.ZodTypeDef,
  TransactionListResponse
> = z.object({
  data: z.array(Transaction$outboundSchema),
  meta: z.lazy(() => TransactionListResponseMeta$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransactionListResponse$ {
  /** @deprecated use `TransactionListResponse$inboundSchema` instead. */
  export const inboundSchema = TransactionListResponse$inboundSchema;
  /** @deprecated use `TransactionListResponse$outboundSchema` instead. */
  export const outboundSchema = TransactionListResponse$outboundSchema;
  /** @deprecated use `TransactionListResponse$Outbound` instead. */
  export type Outbound = TransactionListResponse$Outbound;
}

export function transactionListResponseToJSON(
  transactionListResponse: TransactionListResponse,
): string {
  return JSON.stringify(
    TransactionListResponse$outboundSchema.parse(transactionListResponse),
  );
}

export function transactionListResponseFromJSON(
  jsonString: string,
): SafeParseResult<TransactionListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionListResponse' from JSON`,
  );
}
