/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Current status. Possible values: initiating, pending, completed, failed, canceled, unknown
 */
export const TransactionStatus = {
  Initiating: "initiating",
  Pending: "pending",
  Completed: "completed",
  Failed: "failed",
  Canceled: "canceled",
  Unknown: "unknown",
} as const;
/**
 * Current status. Possible values: initiating, pending, completed, failed, canceled, unknown
 */
export type TransactionStatus = ClosedEnum<typeof TransactionStatus>;

/** @internal */
export const TransactionStatus$inboundSchema: z.ZodNativeEnum<
  typeof TransactionStatus
> = z.nativeEnum(TransactionStatus);
/** @internal */
export const TransactionStatus$outboundSchema: z.ZodNativeEnum<
  typeof TransactionStatus
> = TransactionStatus$inboundSchema;
