/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Transaction, Transaction$inboundSchema } from "./transaction.js";

export type TransactionListResponseMeta = {
  /**
   * Cursor for pagination, representing the last item from the previous page
   */
  cursor: string | null;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
};

/**
 * List of all transactions
 */
export type TransactionListResponse = {
  data: Array<Transaction>;
  meta: TransactionListResponseMeta;
};

/** @internal */
export const TransactionListResponseMeta$inboundSchema: z.ZodType<
  TransactionListResponseMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.nullable(z.string()),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});

export function transactionListResponseMetaFromJSON(
  jsonString: string,
): SafeParseResult<TransactionListResponseMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionListResponseMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionListResponseMeta' from JSON`,
  );
}

/** @internal */
export const TransactionListResponse$inboundSchema: z.ZodType<
  TransactionListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Transaction$inboundSchema),
  meta: z.lazy(() => TransactionListResponseMeta$inboundSchema),
});

export function transactionListResponseFromJSON(
  jsonString: string,
): SafeParseResult<TransactionListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionListResponse' from JSON`,
  );
}
