/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Validation = {
  /**
   * The name of the field that failed validation
   */
  field: string;
  /**
   * The validation error message for the field
   */
  message: string;
};

export type ValidationErrorError = {
  /**
   * HTTP status code of the error
   */
  status: number;
  /**
   * Machine-readable error name
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * List of field-specific validation issues
   */
  validation: Array<Validation>;
};

/** @internal */
export const Validation$inboundSchema: z.ZodType<
  Validation,
  z.ZodTypeDef,
  unknown
> = z.object({
  field: z.string(),
  message: z.string(),
});

/** @internal */
export type Validation$Outbound = {
  field: string;
  message: string;
};

/** @internal */
export const Validation$outboundSchema: z.ZodType<
  Validation$Outbound,
  z.ZodTypeDef,
  Validation
> = z.object({
  field: z.string(),
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Validation$ {
  /** @deprecated use `Validation$inboundSchema` instead. */
  export const inboundSchema = Validation$inboundSchema;
  /** @deprecated use `Validation$outboundSchema` instead. */
  export const outboundSchema = Validation$outboundSchema;
  /** @deprecated use `Validation$Outbound` instead. */
  export type Outbound = Validation$Outbound;
}

export function validationToJSON(validation: Validation): string {
  return JSON.stringify(Validation$outboundSchema.parse(validation));
}

export function validationFromJSON(
  jsonString: string,
): SafeParseResult<Validation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Validation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Validation' from JSON`,
  );
}

/** @internal */
export const ValidationErrorError$inboundSchema: z.ZodType<
  ValidationErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
  validation: z.array(z.lazy(() => Validation$inboundSchema)),
});

/** @internal */
export type ValidationErrorError$Outbound = {
  status: number;
  code: string;
  message: string;
  validation: Array<Validation$Outbound>;
};

/** @internal */
export const ValidationErrorError$outboundSchema: z.ZodType<
  ValidationErrorError$Outbound,
  z.ZodTypeDef,
  ValidationErrorError
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
  validation: z.array(z.lazy(() => Validation$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ValidationErrorError$ {
  /** @deprecated use `ValidationErrorError$inboundSchema` instead. */
  export const inboundSchema = ValidationErrorError$inboundSchema;
  /** @deprecated use `ValidationErrorError$outboundSchema` instead. */
  export const outboundSchema = ValidationErrorError$outboundSchema;
  /** @deprecated use `ValidationErrorError$Outbound` instead. */
  export type Outbound = ValidationErrorError$Outbound;
}

export function validationErrorErrorToJSON(
  validationErrorError: ValidationErrorError,
): string {
  return JSON.stringify(
    ValidationErrorError$outboundSchema.parse(validationErrorError),
  );
}

export function validationErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<ValidationErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ValidationErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ValidationErrorError' from JSON`,
  );
}
