/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Validation = {
  /**
   * The name of the field that failed validation
   */
  field: string;
  /**
   * The validation error message for the field
   */
  message: string;
};

export type ValidationErrorError = {
  /**
   * HTTP status code of the error
   */
  status: number;
  /**
   * Machine-readable error name
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * List of field-specific validation issues
   */
  validation: Array<Validation>;
};

/** @internal */
export const Validation$inboundSchema: z.ZodType<
  Validation,
  z.ZodTypeDef,
  unknown
> = z.object({
  field: z.string(),
  message: z.string(),
});

export function validationFromJSON(
  jsonString: string,
): SafeParseResult<Validation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Validation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Validation' from JSON`,
  );
}

/** @internal */
export const ValidationErrorError$inboundSchema: z.ZodType<
  ValidationErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number(),
  code: z.string(),
  message: z.string(),
  validation: z.array(z.lazy(() => Validation$inboundSchema)),
});

export function validationErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<ValidationErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ValidationErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ValidationErrorError' from JSON`,
  );
}
